/** based on document
 * 
 *  Bundeseinheitliches Positionsnummernverzeichnis für Leistungen häusliche Krankenpflege und Haushaltshilfe
 * 
 * see docs/documents.md for more info
 */

/** 6-character code:
 *  
 * ```
 * gesetzliche Lebensgrundlage
 *  │  Versorgungsart
 *  │   |  Vergütungsart
 * ┌┴─┐┌┴┐┌┴─┐
 *  XX  X  XX
 * ```
 */
export type HaeuslicheKrankenpflegePositionsnummer = {
    gesetzlicheLebensgrundlage: GesetzlicheLebensgrundlageSchluessel,
    versorgungsArt: VersorgungsArtSchluessel,
    verguetungsArt: VerguetungsArtSchluessel,
}

/** We need to differentate between positionsnummern that are pauschale and that are not because
 *  they are handled very differently when transferring
 */
export type HaeuslicheKrankenpflegeEinzelPositionsnummer = {
    gesetzlicheLebensgrundlage: GesetzlicheLebensgrundlageSchluessel,
    versorgungsArt: VersorgungsArtSchluessel,
    verguetungsArt: EinzelVerguetungsArtSchluessel,
}

export type HaeuslicheKrankenpflegePauschalePositionsnummer = {
    gesetzlicheLebensgrundlage: GesetzlicheLebensgrundlageSchluessel,
    versorgungsArt: VersorgungsArtSchluessel,
    verguetungsArt: PauschaleVerguetungsArtSchluessel,
}

export const haeuslicheKrankenpflegePositionsnummerCode = (n: HaeuslicheKrankenpflegePositionsnummer): string =>
    n.gesetzlicheLebensgrundlage + n.versorgungsArt + n.verguetungsArt

/** Stelle 1-2 der Positionsnummer */
export const gesetzlicheLebensgrundlageSchluessel = {
    "01": "Häusliche Krankenpflege nach § 37 Abs. 1 Satz 1 SGB V",
    "02": "Häusliche Krankenpflege nach § 37 Abs. 1 Satz 5 SGB V",
    "03": "Häusliche Krankenpflege nach § 37 Abs. 2 Satz 1 SGB V",
    "04": "Häusliche Krankenpflege nach § 37 Abs. 2 Satz 4 SGB V",
    "05": "Haushaltshilfe nach § 38 Abs. 1 SGB V",
    "06": "Haushaltshilfe nach § 38 Abs. 2 SGB V",
    "07": "Häusliche Pflege nach § 24g SGB V (neu durch PNG)",
    "08": "Haushaltshilfe nach § 24h SGB V (neu durch PNG)",
    "09": "Häusliche Krankenpflege nach § 37 Abs. 2 Satz 3 SGB V",
    "10": "Häusliche Krankenpflege nach § 37 Abs. 1a SGB V (Regelleistung) bis zu 4 Wochen",
    "11": "Häusliche Krankenpflege nach § 37 Abs. 1a SGB V (Ermessensleistung) über 4 Wochen",
    "13": "Häusliche Krankenpflege nach § 37 Abs. 2 Satz 8 SGB V (gültig)",
    "14": "Ergänzender HKP-Anspruch § 37 Abs. 2 Satz 3 SGB V / Finanzierungsbestandteile aus SGBXI"
}
export type GesetzlicheLebensgrundlageSchluessel = keyof typeof gesetzlicheLebensgrundlageSchluessel

/** Stelle 3 der Positionsnummer */
export const versorgungsArtSchluessel = {
    "1": "Grundpflege",
    "2": "Behandlungspflege",
    "3": "Hauswirtschaftliche Versorgung",
    "4": "Kombi aus Grund-/Behandlungspflege/hauswirtschaftlicher Versorgung",
    "5": "Hauptberufliche Haushaltshilfe mit staatl. Anerkennung",
    "6": "Hauptberufliche Haushaltshilfe ohne staatl. Anerkennung",
    "7": "Nebenberufliche Haushaltshilfe mit staatl. Anerkennung",
    "8": "Nebenberufliche Haushaltshilfe ohne staatl. Anerkennung",
    "9": "Kombi aus Grund- und Behandlungspflege",
    "0": "Kombi aus Grundpflege und hauswirtschaftlicher Versorgung",
    "A": "ambulante intensivpflegerische Versorgung im Rahmen der Häuslichen Krankenpflege"
}
export type VersorgungsArtSchluessel = keyof typeof versorgungsArtSchluessel

/** Stelle 4-6 der Positionsnummer */
export type VerguetungsArtSchluessel = 
    PauschaleVerguetungsArtSchluessel |
    EinzelVerguetungsArtSchluessel

export type EinzelVerguetungsArtSchluessel = 
    AllgemeinVerguetungsArtSchluessel |
    EinzelleistungenVerguetungsArtSchluessel |
    ZuschlaegeAbzuegeVerguetungsArtSchluessel |
    HausbesucheWegegeldVerguetungsArtSchluessel |
    HKPAnspruchSGBXIVerguetungsArtSchluessel

/** Allgemein */
export const allgemeinVerguetungsArtSchluessel = {
    "000": "keine besondere Ausprägung"
}
export type AllgemeinVerguetungsArtSchluessel = keyof typeof allgemeinVerguetungsArtSchluessel

/** Pauschalen */
export const pauschaleVerguetungsArtSchluessel = {
    "100": "Pauschale für 24 Std. Pflege",
    "101": "Tagpauschale",
    "102": "Nachtpauschale",
    "103": "Wochenendpauschale",
    "104": "Samstagspauschale",
    "105": "Sonn- und Feiertagspauschale",
    "106": "Sonderpauschale",
    "107": "Tagespauschale (Einsatz 1 x tägl.)",
    "108": "Tagespauschale (Einsatz 2 x tägl.)",
    "109": "Tagespauschale (Einsatz 3 x tägl.)",
    "909": "Tagespauschale dauerhaft invasiv beatmete Menschen",
    "910": "Tagespauschale intermittierende invasiv beatmete Menschen",
    "911": "Tagespauschale nicht invasiv beatmete Menschen",
    "912": "Tagespauschale s.c. Infusion",
    "110": "Pauschale bis zu 30 Minuten",
    "111": "Pauschale je Stunde",
    "112": "Pauschale bis 2 Stunden",
    "113": "Pauschale von über 2 bis 4 Stunden",
    "114": "Pauschale von über 4 bis 6 Stunden",
    "115": "Pauschale von über 6 bis 8 Stunden",
    "116": "Pauschale je weitere Stunde",
    "117": "Pauschale je Stunde (für die 1. bis 4. Stunde)",
    "118": "Pauschale je 15 Minuten",
    "120": "Einsatzpauschale",
    "121": "Pauschale 1. Einsatz",
    "122": "Pauschale 2. Einsatz",
    "123": "Pauschale 3. Einsatz",
    "124": "Pauschale 1. und 2. Einsatz",
    "125": "Pauschale 2. und 3. Einsatz",
    "126": "Pauschale 1., 2. und 3. Einsatz",
    "127": "Pauschale je Einsatz in Wohngemeinschaften, Wohnanlagen u.ä.",
    "128": "Pauschale je Einsatz im Haushalt bei zwei u. mehr Personen",
    "129": "Pauschale je Einsatz bei Kombi. von SGB XI u. SGB V Leistungen",
    "130": "Pauschale einschließlich hauswirtschaftliche Versorgung",
    "131": "Pauschale zu ungünstigen Zeiten",
    "132": "Einsatzpauschale für Leistungen der psychiatrischen häusl. Krankenpflege",
    "133": "Einsatzpauschale - häusl. Krankenpflege für Kinder - je Stunde",
    "134": "Einsatzpauschale für Leistungen der psychiatrischen und somatischen häuslichen Krankenpflege",
    "135": "Einsatzpauschale für Leistungen der psychiatrischen häuslichen Krankenpflege ohne somatische Krankenpflege; für Krankheitsbilder F 04.- bis F 41.1",
    "136": "Einsatzpauschale für Leistungen der psychiatrischen und somatischen häuslichen Krankenpflege; für Krankheitsbilder F 04.- bis F 41.1",
    "137": "Einsatzpauschale für Leistungen der psychiatrischen häuslichen Krankenpflege ohne somatische Krankenpflege; für Krankheitsbilder F 00.1 bis F 02.8",
    "138": "Einsatzpauschale für Leistungen der psychiatrischen und somatischen häuslichen Krankenpflege; für Krankheitsbilder F 00.1 bis F 02.8",
    "139": "Höchstbetrag je Tag für Leistungen der psychiatrischen häuslichen Krankenpflege ohne somatische Krankenpflege",
    "140": "Höchstbetrag je Tag",
    "141": "Höchstbetrag je Nacht",
    "142": "Höchstbetrag je Tag und Nacht",
    "143": "Höchstbetrag je Einsatz",
    "144": "Höchstbetrag für Überwachung von Sondennahrung/Infusion/en bei Kombination von SGB XI und SGB V Leistungen ",
    "145": "Höchstbetrag für Überwachung von Sondennahrung/Infusion/en in Betreutem Wohnen",
    "146": "Höchstbetrag für Überwachung von Sondennahrung/Infusion/en bei zwei und mehr Personen im Haushalt",
    "147": "Pauschale für die Kombination einzelner Leistungen",
    "148": "Intensivpflege Tagespauschale",
    "149": "Intensivpflege Monatspauschale",
    "150": "Pauschale für den Einsatz von zwei Pflegekräften",
    "151": "Pauschale für den Einsatz von Pflegekräften mit einjähriger Ausbildung",
    "152": "Pauschale für den Einsatz von Pflegekräften mit einjähriger Ausbildung in betreutem Wohnen",
    "153": "Pauschale für den Einsatz von Pflegekräften mit einjähriger Ausbildung bei zwei u. mehr Personen im Haushalt",
    "154": "Pauschale für den Einsatz von Pflegekräften mit einjähriger Ausbildung bei Kombi. von SGB XI und SGB V Leistungen",
    "155": "Einsatz von Pflegefachkräften 1 x tägl. (Tagespauschale)",
    "156": "Einsatz von Pflegefachkräften 2 x tägl. (Tagespauschale)",
    "157": "Einsatz von Pflegefachkräften 3 x tägl. (Tagespauschale)",
    "158": "Einsatzpauschale - häusliche Krankenpflege für Kinder - 30",
    "159": "Einsatzpauschale - häusliche Krankenpflege für Kinder - 2 Stunden",
    "160": "Monatspauschale (einmal tägl. Leistungserbringung)",
    "161": "Monatspauschale (zweimal tägl. Leistungserbringung)",
    "162": "Monatspauschale (dreimal tägl. Leistungserbringung)",
    "163": "Pauschale für aufwendige Pflege (einmal täglich)",
    "164": "Pauschale für aufwendige Pflege (zweimal täglich)",
    "165": "Pauschale für aufwendige Pflege (dreimal täglich)",
    "166": "Pauschale für sonstige Pflege (einmal täglich)",
    "167": "Pauschale für sonstige Pflege (zweimal täglich)",
    "168": "Pauschale für sonstige Pflege (dreimal täglich)",
    "170": "Pauschale für Leistungsgruppe 1 (Behandlungspflegen I)",
    "171": "Pauschale für Leistungsgruppe 2 (Behandlungspflegen II)",
    "172": "Pauschale für Leistungsgruppe 3 (Behandlungspflegen III)",
    "173": "Pauschale für Leistungsgruppe 4 (Behandlungspflegen IV)",
    "174": "Pauschale für Leistungsgruppe 5 (Behandlungspflegen V)",
    "175": "Pauschale für Leistungsgruppe 5 (Behandlungspflegen VI)",
    "176": "Pauschale für Leistungsgruppe 5 (Behandlungspflegen VII)",
    "177": "Hauswirtschaftliche Versorgung im Zusammenhang mit der Grundpflege",
    "178": "Psychiatrische Krankenpflege und somatische Krankenpflege LG 4",
    "179": "Psychiatrische Krankenpflege und somatische Krankenpflege LG 5",
    "180": "Tagespauschale Behandlungspflege I bei vier und mehr Einsätzen pro Tag",
    "181": "Tagespauschale Behandlungspflege II bei vier und mehr Einsätzen pro Tag",
    "182": "Tagespauschale Behandlungspflege III bei vier und mehr Einsätzen pro Tag",
    "183": "Tagespauschale Behandlungspflege IV bei maximal drei Einsätzen pro Tag",
    "184": "Tagespauschale zur Anleitung bei der Behandlungspflege I bei vier und mehr Einsätzen pro Tag",
    "185": "Tagespauschale zur Anleitung bei der Behandlungspflege II bei vier und mehr Einsätzen pro Tag",
    "186": "Tagespauschale zur Anleitung bei der Behandlungspflege III bei vier und mehr Einsätzen pro Tag",
    "187": "Tagespauschale zur Anleitung bei der Behandlungspflege IV bei maximal drei Einsätzen pro Tag",
    // the following are invalid since 2005/06
    //"188": "Wegepauschale (für den 1. und 2. Einsatz) gültig bis 30.6.2005",
    //"189": "Wegepauschale (für den 3. - 5. Einsatz) gültig bis 30.6.2005",
    //"190": "Wegepauschale bei zeitgleicher Leistungserbringung nach SGB V / SGB XI (1. und 2. Einsatz) gültig bis 30.6.2005",
    //"191": "Wegepauschale bei zeitgleicher Leistungserbringung nach SGB V / SGB XI (3. - 5. Einsatz) gültig bis 30.6.2005",
    "192": "Anleitung zum Anlegen und Wechseln von Wundverbänden oder Kompressionsverbänden (Einsatzpauschale)",
    "193": "Anlegen und Wechseln von Wundverbänden oder Kompressinonsverbänden (Einsatzpauschale)",
    "194": "Betreuungsstunde bei Betreuung von mehr als einem Kind bis zu 3 Jahren oder Betreuung eines behinderten Kindes",
    "195": "Teilstunden sind in Teilbeträgen abrechenbar",
    "196": "Psychiatrische Krankenpflege und somatische Krankenpflege LG 1",
    "197": "Psychiatrische Krankenpflege und somatische Krankenpflege LG 2",
    "198": "Psychiatrische Krankenpflege und somatische Krankenpflege LG 3",
    "199": "Medikamentengabe (Deckelungspauschale)",
    "790": "Stundenpauschale für Intensivpflege",
    "791": "Stundenpauschale für Kinderintensivpflege, Kinderkrankenpflege",
    "792": "Stundenpauschale für Intensivpflege (Erwachsene)",
    "801": "Tagespauschale \"Intensivpflege\", für die ersten 7 Tage",
    "802": "Tagespauschale \"Intensivpflege\", für die 8. Bis 21. Tag",
    "803": "Tagespauschale \"Intensivpflege\", vom 22. Tag an",
    "804": "Tagespauschale \"physikalische Leistung\", für die ersten 2 Tage",
    "805": "Tagespauschale \"physikalische Leistung\", vom 3. Tag an",
    "806": "Tagespauschale \"Onkologiepflege\", für die ersten 7 Tage",
    "807": "Tagespauschale \"Onkologiepflege\", vom 8. Tag an",
    "808": "Tagespauschale \"Ambulante Palliativpflege\"",
    "809": "Pauschale für den Einsatz von Pflegefachkräften in Betreutem Wohnen",
    "810": "Pauschale für den Einsatz von Pflegefachkräften bei zwei u. mehr Personen im Haushalt",
    "811": "Pauschale für den Einsatz von Pflegefachkräften bei Kombination von SGB XI und SGB V Leistungen",
    "812": "Psychiatrische Krankenpflege ohne somatische Krankenpflege LG 1",
    "813": "Psychiatrische Krankenpflege ohne somatische Krankenpflege LG 2",
    "814": "Psychiatrische Krankenpflege ohne somatische Krankenpflege LG 3",
    "815": "Tagespauschale amb. Finalpflege, mind. 5 max. 10 Einsätze",
    "816": "Einsatzpauschale amb. Finalpflege bei mehr als 10 Einsätzen täglich, je Einsatz",
    "817": "Pauschale für Anleitung LG 1 (Anleitung Behandlungspflege I)",
    "818": "Pauschale für Anleitung LG 2 (Anleitung Behandlungspflege II)",
    "819": "Pauschale für Anleitung LG 3 (Anleitung Behandlungspflege III)",
    "820": "Pauschale für Anleitung LG 4 (Anleitung Behandlungspflege IV)",
    "821": "Höchstbetrag Gruppe A je Einsatz",
    "822": "Höchstbetrag Gruppe B je Einsatz",
    "823": "Höchstbetrag Gruppe C je Einsatz",
    "824": "Pauschale je Einsatz in Wohngemeinschaften, Wohnanlagen u. ä. an Sonn- und Feiertagen",
    "825": "Kleine Behandlungspflege je Einsatz",
    "826": "Mittlere Behandlungspauschale je Einsatz",
    "827": "Große Behandlungspauschale je Einsatz",
    "828": "Höchstbetrag Anleitungen zur Behandlungspflege",
    "829": "Tagespauschale Behandlungspflege LG 1",
    "830": "Tagespauschale Behandlungspflege LG 2",
    "831": "Tagespauschale Behandlungspflege LG 3",
    "832": "Tagespauschale Behandlungspflege LG 4",
    "833": "Tagespauschale Behandlungspflege LG 5",
    "834": "Monatspauschale Intensivpflege, tgl. Einsatz 8 - 12 Std.",
    "835": "Monatspauschale Intensivpflege, tgl. Einsatz über 12 - 16 Std.",
    "836": "Monatspauschale Intensivpflege, tgl. Einsatz über 16 - 20 Std.",
    "837": "Monatspauschale Intensivpflege, tgl. Einsatz über 20 - 24 Std.",
    "838": "Einsatzpauschale für Leistungen der psychiatrischen und somatischen häuslichen Krankenpflege, 5 Minuten",
    "839": "Einsatzpauschale für Leistungen der psychiatrischen und somatischen häuslichen Krankenpflege, 30 Minuten",
    "840": "Pauschale für Leistungsgruppe 1 in Wohnanlagen, Wohngemeinschaften, betreutes Wohnen",
    "841": "Pauschale für Leistungsgruppe 2 in Wohnanlagen, Wohngemeinschaften, betreutes Wohnen",
    "842": "Pauschale für Leistungsgruppe 3 in Wohnanlagen, Wohngemeinschaften, betreutes Wohnen",
    "843": "Pauschale für Leistungsgruppe 3a in Wohnanlagen, Wohngemeinschaften, betreutes Wohnen",
    "844": "Pauschale für Leistungsgruppe 3b in Wohnanlagen, Wohngemeinschaften, betreutes Wohnen",
    "845": "Anleitungserfolg Leistungsgruppe 1",
    "846": "Anleitungserfolg Leistungsgruppe 2",
    "847": "Anleitungserfolg Leistungsgruppe 3",
    "848": "Anleitungserfolg Leistungsgruppe 4",
    "849": "Einsatzpauschale 1. - 10. Stunde - je Stunde",
    "850": "Einsatzpauschale 11. - 18. Stunde - je Stunde",
    "851": "Einsatzpauschale 19. - 24. Stunde - je Stunde",
    "852": "Stundenvergütung Intensivpflege bis 7 Stunden täglich",
    "853": "Stundenvergütung Intensivpflege ab 8 Stunden täglich",
    "854": "Stundenvergütung Intensivpflege ab 12 Stunden täglich",
    "855": "Stundenvergütung Intensivpflege ab 16 Stunden täglich",
    "856": "Stundenvergütung Kinder-Intensivpflege bis 7 Stunden täglich",
    "857": "Stundenvergütung Kinder-Intensivpflege ab 8 Stunden täglich",
    "858": "Stundenvergütung Kinder-Intensivpflege ab 12 Stunden täglich",
    "859": "Stundenvergütung Kinder-Intensivpflege ab 16 Stunden täglich",
    "860": "Stundenvergütung Intensivpflege 'Betreutes Wohnen'",
    "861": "1. Einsatz in Wohngemeinschaften, Wohnanlagen o.ä.",
    "862": "1. und 2. Einsatz in Wohngemeinschaften, Wohnanlagen o.ä.",
    "863": "1., 2. und 3. Einsatz in Wohngemeinschaften, Wohnanlagen o.ä.",
    "864": "Pauschale Pflegestufen übergreifende für häusliche Krankenpflege in Heimen bei Personengruppen mit besonders hohem behandlungspflegerischem Versorgungsbedarf",
    "865": "Pauschale Pflegestufe I für häusliche Krankenpflege in Heimen bei Personengruppen mit besonders hohem behandlungspflegerischem Versorgungsbedarf",
    "866": "Pauschale Pflegestufe II für häusliche Krankenpflege in Heimen bei Personengruppen mit besonders hohem behandlungspflegerischem Versorgungsbedarf",
    "867": "Pauschale Pflegestufe III für häusliche Krankenpflege in Heimen bei Personengruppen mit besonders hohem behandlungspflegerischem Versorgungsbedarf",
    "868": "Tagespauschale Behandlungspflege 0 (bei vier und mehr Einsätzen pro Tag)",
    "869": "Stundenvergütung Intensivpflege bis \"10 Stunden täglich\" Pauschale",
    "870": "Stundenvergütung Intensivpflege bis \"18 Stunden täglich\" Pauschale",
    "871": "Stundenvergütung Intensivpflege bis \"24 Stunden täglich\" Pauschale",
    "872": "Stundenvergütung Kinder-Intensivpflege bis \"10 Stunden täglich\" Pauschale",
    "873": "Stundenvergütung Kinder-Intensivpflege bis \"18 Stunden täglich\" Pauschale",
    "874": "Stundenvergütung Kinder-Intensivpflege bis \"24 Stunden täglich\" Pauschale",
    "917": "Pauschale (Intensivpflege) je Stunde bei einer gleichzeitigen Betreuung von zwei oder mehreren Patienten je Pflegekraft",
    "875": "Anteilige Wegepauschale",
    "876": "Minimalwegepauschale",
    "877": "Hälftige Wegepauschale 1",
    "878": "Hälftige Wegepauschale 2",
    "879": "Hälftige Wegepauschale 3",
    "880": "Pauschale für Leistungsgruppe 0 (Behandlungspflegen 0)",
    "881": "Tagespauschale zur Anleitung bei der Behandlungspflege IV bei vier und mehr Einsätzen pro Tag",
    "882": "Pauschale für die Behandlungspflege in Heimen - Wachkoma/Apalliker",
    "883": "Pauschale für die Behandlungspflege in Heimen - Beatmung",
    "884": "Monatsvergütung Intensivpflege - Betreutes Wohnen",
    "885": "Pauschale für die Zusendung von Unterlagen (Begutachtungsfall) durch den Leistungserbringer",
    "886": "Pauschale für die Zusendung von Unterlagen (Begutachtungsfall) inkl. schriftlicher Stellungnahme durch den Leistungserbringer",
    "887": "Behandlungspflege 0 für schwerstkranke Kinder",
    "888": "Behandlungspflege 1 für schwerstkranke Kinder",
    "889": "Behandlungspflege 2 für schwerstkranke Kinder",
    "890": "Behandlungspflege 3 für schwerstkranke Kinder",
    "891": "Behandlungspflege 4 für schwerstkranke Kinder",
    "892": "Behandlungspflege 5 für schwerstkranke Kinder",
    "893": "Reinigungspauschale",
    "894": "Fixierungspauschale",
    "895": "Kompressionspauschale",
    "920": "MRSA Tagespauschale ohne SGB XI",
    "921": "MRSA Tagespauschale mit SGB XI",
    "924": "MRSA-Eradikation für Versicherte mit Anspruch auf Leistungen nach SGB XI",
    "925": "MRSA-Eradikation für Versicherte ohne Anspruch auf Leistungen nach SGB XI",
    "926": "Stundenvergütung Kinder-Intensivpflege bis \"12 Stunden täglich\" Pauschale",
    "A20": "Intensivpflegerische Kinderversorgung für die Minutenpreise",
    "A21": "Behandlungspflege und Betreuungszeit Intensivpflege WG Nr. 1 - Stunden",
    "A22": "Behandlungspflege und Betreuungszeit Intensivpflege WG Nr. 1 - Minuten",
    "A23": "Behandlungspflege und Betreuungszeit Intensivpflege WG Nr. 2 - Stunden",
    "A24": "Behandlungspflege und Betreuungszeit Intensivpflege WG Nr. 2 - Minuten",
    "A25": "Behandlungspflege und Betreuungszeit Intensivpflege WG Nr. 3 - Stunden",
    "A26": "Behandlungspflege und Betreuungszeit Intensivpflege WG Nr. 3 - Minuten",
    "A27": "Behandlungspflege und Betreuungszeit Intensivpflege WG Nr. 4 - Stunden",
    "A28": "Behandlungspflege und Betreuungszeit Intensivpflege WG Nr. 4 - Minuten",
    "A29": "Behandlungspflege und Betreuungszeit Intensivpflege WG Nr. 5 - Stunden",
    "A30": "Behandlungspflege und Betreuungszeit Intensivpflege WG Nr. 5 - Minuten",
    "A31": "Behandlungspflege und Betreuungszeit Intensivpflege WG Nr. 6 - Stunden",
    "A32": "Behandlungspflege und Betreuungszeit Intensivpflege WG Nr. 6 - Minuten",
    "A33": "WG 1 TP PG 0/1 KV/PV 28 - 31 Intensivpflege",
    "A34": "WG 1 TP PG 2 KV/PV 31 Intensivpflege",
    "A35": "WG 1 TP PG 2 KV/PV 30 Intensivpflege",
    "A36": "WG 1 TP PG 2 KV/PV 29 Intensivpflege",
    "A37": "WG 1 TP PG 2 KV/PV 28 Intensivpflege",
    "A38": "WG 1 TP PG 3 KV/PV 31 Intensivpflege",
    "A39": "WG 1 TP PG 3 KV/PV 30 Intensivpflege",
    "A40": "WG 1 TP PG 3 KV/PV 29 Intensivpflege",
    "A41": "WG 1 TP PG 3 KV/PV 28 Intensivpflege",
    "A42": "WG 1 TP PG 4 KV/PV 31 Intensivpflege",
    "A43": "WG 1 TP PG 4 KV/PV 30 Intensivpflege",
    "A44": "WG 1 TP PG 4 KV/PV 29 Intensivpflege",
    "A45": "WG 1 TP PG 4 KV/PV 28 Intensivpflege",
    "A46": "WG 1 TP PG 5 KV/PV 31 Intensivpflege",
    "A47": "WG 1 TP PG 5 KV/PV 30 Intensivpflege",
    "A48": "WG 1 TP PG 5 KV/PV 29 Intensivpflege",
    "A49": "WG 1 TP PG 5 KV/PV 28 Intensivpflege",
    "A50": "WG 2 TP PG 0/1 KV/PV 28 - 31 Intensivpflege",
    "A51": "WG 2 TP PG 2 KV/PV 31 Intensivpflege",
    "A52": "WG 2 TP PG 2 KV/PV 30 Intensivpflege",
    "A53": "WG 2 TP PG 2 KV/PV 29 Intensivpflege",
    "A54": "WG 2 TP PG 2 KV/PV 28 Intensivpflege",
    "A55": "WG 2 TP PG 3 KV/PV 31 Intensivpflege",
    "A56": "WG 2 TP PG 3 KV/PV 30 Intensivpflege",
    "A57": "WG 2 TP PG 3 KV/PV 29 Intensivpflege",
    "A58": "WG 2 TP PG 3 KV/PV 28 Intensivpflege",
    "A59": "WG 2 TP PG 4 KV/PV 31 Intensivpflege",
    "A60": "WG 2 TP PG 4 KV/PV 30 Intensivpflege",
    "A61": "WG 2 TP PG 4 KV/PV 29 Intensivpflege",
    "A62": "WG 2 TP PG 4 KV/PV 28 Intensivpflege",
    "A63": "WG 2 TP PG 5 KV/PV 31 Intensivpflege",
    "A64": "WG 2 TP PG 5 KV/PV 30 Intensivpflege",
    "A65": "WG 2 TP PG 5 KV/PV 29 Intensivpflege",
    "A66": "WG 2 TP PG 5 KV/PV 28 Intensivpflege",
    "A67": "092864 = Pauschale Pflegegrade für häusliche Krankenpflege in Heimen bei Personengruppen mit besonders hohem behandlungspflegerischem Versorgungsbedarf",
    "A68": "092865 = Pauschale Pflegegrad 1 für häusliche Krankenpflege in Heimen bei Personengruppen mit besonders hohem behandlungspflegerischem Versorgungsbedarf",
    "A69": "092866 = Pauschale Pflegegrad 2 für häusliche Krankenpflege in Heimen bei Personengruppen mit besonders hohem behandlungspflegerischem Versorgungsbedarf",
    "A70": "098867 = Pauschale Pflegegrad 3 für häusliche Krankenpflege in Heimen bei Personengruppen mit besonders hohem behandlungspflegerischem Versorgungsbedarf",
    "A71": "Pauschale Pflegegrad 4 für häusliche Krankenpflege in Heimen bei Personengruppen mit besonders hohem behandlungspflegerischem Versorgungsbedarf",
    "A72": "Pauschale Pflegegrad 5 für häusliche Krankenpflege in Heimen bei Personengruppen mit besonders hohem behandlungspflegerischem Versorgungsbedarf",
    "A77": "Behandlungspflege in vollstationären Einrichtungen für Personen mit besonders hohem behandlungspflegerischen Versorgungsbedarf (Monatsbetrag)",
    "A78": "Behandlungspflege in vollstationären Einrichtungen für Personen mit besonders hohem behandlungspflegerischen Versorgungsbedarf (Monatsbetrag bei Abwesenheit)",
    "A79": "Behandlungspflege in vollstationären Einrichtungen für Personen mit besonders hohem behandlungspflegerischen Versorgungsbedarf (Tagesbetrag)",
    "A80": "Behandlungspflege in vollstationären Einrichtungen für Personen mit besonders hohem behandlungspflegerischen Versorgungsbedarf (Tagesbetrag bei Abwesenheit)",
    "A81": "Pauschale für häusliche Krankenpflege in Heimen bei Personengruppen mit einem besonders hohen behandlungspflegerischen Versorgungsbedarf und einem Pflegegrad II",
    "A82": "Pauschale für häusliche Krankenpflege in Heimen bei Personengruppen mit einem besonders hohen behandlungspflegerischen Versorgungsbedarf und einem Pflegegrad III",
    "A83": "Pauschale für häusliche Krankenpflege in Heimen bei Personengruppen mit einem besonders hohen behandlungspflegerischen Versorgungsbedarf und einem Pflegegrad IV",
    "A84": "Pauschale für häusliche Krankenpflege in Heimen bei Personengruppen mit einem besonders hohen behandlungspflegerischen Versorgungsbedarf und einem Pflegegrad V",
    "A85": "Stundenvergütung Intensivpflege \"betreutes Wohnen\" in Kleinst-WG",
    "A89": "Symptomkontrolle als Komplexleistung (24a)",
    "B12": "Intensivbehandlungspflege Kindergarten/Schule",
    "B13": "Intensivbehandlungspflege mit Trachealkanüle",
    "B14": "Sonstige Intensivbehandlungspflege",
    "B15": "Invasive Beatmungspflege",
    "B16": "Nicht invasive Beatmungspflege",
    "B17": "Pauschale für Häusliche Krankenpflege",
    "B18": "Pauschale für Häusliche Krankenpflege Kindergarten/Schule",
    "B21": "Anziehen von Kompressionsstrümpfen der Druckklasse 1",
    "B23": "Symptomkontrolle als Tagespauschale (24a)",
    "B24": "Symptomkontrolle bei Palliativpatientinnen und Palliativpatienten - Leistungsbeginn-Pauschale",
    "B25": "Symptomkontrolle bei Palliativpatientinnen und Palliativpatienten - Tagespauschale 1 - Erstverordnung",
    "B26": "Symptomkontrolle bei Palliativpatientinnen und Palliativpatienten - Tagespauschale 2 - Folgeverordnung",
    "B27": "Symptomkontrolle bei Palliativpatientinnen und Palliativpatienten - Finalpauschale",
    "B44": "Intensivpflege in ambulanten Wohneinrichtungen (Kinder)",
    "B45": "Intensivpflege in ambulanten Wohneinrichtungen (Erwachsene)",
    "B54": "Pauschale Behandlungspflege 1a",
    "B55": "Anleitung Behandlungspflege 1a",
    "B56": "Pauschale für Leistungsgruppe 6",
    "B57": "Pauschale für Leistungsgruppe 7",
    "B58": "Pauschale für Leistungsgruppe 8",
    "B59": "Pauschale für Leistungsgruppe 9",
    "B60": "Pauschale für Leistungsgruppe 10",
    "B61": "Pauschale für Leistungsgruppe 11",
    "B62": "Pauschale für Leistungsgruppe 12",
    "B63": "Pauschale für Leistungsgruppe 13",
    "B64": "Pauschale für Leistungsgruppe 14",
    "B65": "Pauschale für Leistungsgruppe 15",
    "B78": "Pauschale für Leistungsgruppe 4a (Behandlungspflege IVa)",
    "B89": "Einsatzpauschale AAPV - Allgemeine ambulante Palliativversorgung (Nr. 24a)",
    "B90": "Pauschale für den Einsatz einer 2. Pflegekraft - Leistungsgruppe 1",
    "B91": "Pauschale für den Einsatz einer 2. Pflegekraft - Leistungsgruppe 2",
    "B92": "Pauschale für den Einsatz einer 2. Pflegekraft - Leistungsgruppe 3",
    "B93": "Pauschale für den Einsatz einer 2. Pflegekraft - Leistungsgruppe 4",
    "B94": "Pauschale für den Einsatz einer 2. Pflegekraft - Leistungsgruppe 5",
    "B95": "Einsatzpauschale MRE - Multiresistente Erreger",
    "B96": "Einsatzpauschale ab der 4. Leistung - Leistungsgruppe 1",
    "B97": "Einsatzpauschale ab der 4. Leistung - Leistungsgruppe 2",
    "B98": "Einsatzpauschale ab der 4. Leistung - Leistungsgruppe 3",
    "B99": "Einsatzpauschale ab der 4. Leistung - Leistungsgruppe 4",
    "C00": "Einsatzpauschale ab der 4. Leistung - Leistungsgruppe 5",
    "C01": "Pauschale für Leistungsgruppe 4a (Behandlungspflege IVa)",
    "C05": "Intensivpflege Kinder 0. – 6. Lebensjahr",
    "C06": "Intensivpflege Kinder 7. – 18. Lebensjahr",
    "C34": "Pauschale je 5 Minuten",
    "C64": "Wundversorgung: pauschale Vergütung für die Erstbehandlung mit Edukation und weitergehenden Inhalten",
    "C65": "Wundversorgung: pauschale Vergütung für die Folgeversorgung mit Edukation und weitergehenden Inhalten",
    "C84": "Tagespauschale NRW",
}
export type PauschaleVerguetungsArtSchluessel = keyof typeof pauschaleVerguetungsArtSchluessel

/** Einzelleistungen */
export const einzelleistungenVerguetungsArtSchluessel = {
    "201": "Blutdruckmessen",
    "202": "Bruchbänder anlegen",
    "203": "Eisbeutel (Kälteträger) verabreichen",
    "204": "Inkontinentenversorgung",
    "205": "Körperpflege, Hilfe bei",
    "206": "Krankenbeobachtung",
    "207": "Ausscheidungen beobachten",
    "208": "Gemütslage",
    "209": "Gewichtskontrolle",
    "210": "Hautkontrolle",
    "211": "Körperhaltungskontrolle",
    "212": "Krankenbeobachtung",
    "213": "Körpertemperaturkontrolle",
    "214": "Pulskontrolle",
    "215": "Schleimhautkontrolle",
    "216": "Magensonde, Überwachung der Lage",
    "217": "Mobilisation, Hilfen bei der",
    "218": "Nahrungsaufnahme, Hilfen bei der",
    "219": "Prothesen, Anlegen der",
    "220": "Sitzwache",
    "221": "Sondennahrung, Verabreichung von",
    "222": "Stomawechsel",
    "223": "Stützkorsett, Anlegen von",
    "224": "Tages- und Wochenplanung, Hilfe bei",
    "225": "Umschläge, Verabreichen von",
    "226": "Vorbeugungsmaßnahmen",
    "227": "Wärmflaschen verabreichen",
    "228": "Wickel verabreichen",
    "229": "Wundschnellverbände (Pflaster) anlegen",
    "230": "Absaugen",
    "231": "Anus-Praeter-Versorgung",
    "232": "Anus-Praeter-Wechsel",
    "233": "Arzneien verabreichen und überwachen",
    "234": "Augen, Gabe von Salbe und Tropfen",
    "235": "Augenspülungen",
    "236": "Bäder, medizinische (Hilfe beim Ein- und Aussteigen + Badezusatz)",
    "237": "Bandagen anlegen",
    "238": "Beatmungsgerät überwachen und warten",
    "239": "Bewegungsübungen",
    "240": "Blutzucker messen",
    "241": "Blasenspülung",
    "242": "Bronchialtoilette/Versorgung der Atemwege",
    "243": "Dekubitusbehandlung und -versorgung",
    "244": "delegierte ärztliche Leistungen",
    "245": "Dialysepatienten versorgen und überwachen",
    "246": "Drainagen, Überwachung von",
    "247": "Einlauf",
    "248": "Einreibungen",
    "249": "Flüssigkeitsbilanzierungen",
    "250": "Gehübungen",
    "251": "Infusionen, Überwachung von",
    "252": "Infusionen bis 30 Minuten",
    "253": "Infusionen mehr als 30 Minuten",
    "254": "Infusionen bis mehr als 90 Minuten",
    "255": "Inhalationen",
    "256": "Injektionen",
    "257": "Injektionen bis zu 2 je Besuch",
    "258": "Injektionen mehr als 2 je Besuch",
    "259": "Instillation",
    "260": "Insulin, Aufziehen von",
    "261": "Kanüle, Wechseln der",
    "262": "Katheterisierung",
    "263": "Kompressionsstrümpfen, An- und Ausziehen von",
    "264": "Lunge, absaugen der",
    "265": "Magensonde, legen und wechseln einer",
    "266": "Mundpflege",
    "267": "Neurologischen Überwachungsbogens, Führung eines",
    "268": "Ohren, Gabe von Salben und Tropfen",
    "269": "Ohrspülung",
    "270": "Physikalische Maßnahmen",
    "271": "Pneumonieprophylaxe",
    "272": "Reaktivierung",
    "273": "Sauerstoff, verabreichen von",
    "274": "Arzneien verabreichen und überwachen (2 x täglich)",
    "275": "Sprechübungen",
    "276": "Stomaversorgung",
    "277": "Arzneien verabreichen und überwachen (3 x täglich)",
    "278": "Untersuchungen",
    "279": "Urinals, Anlagen und Entfernen eines",
    "280": "Venendrucks, Messung des zentralen",
    "281": "Venenkatheter, Überwachung von zentralen",
    "282": "Verbänden, Anlegen und Wechseln von",
    "283": "Wunden, Behandlung und Pflege von",
    "284": "Zuckertest einschließlich Teststreifen",
    "285": "Abfalls, Entsorgen des Haushalts",
    "286": "Beheizen",
    "287": "Botengänge",
    "288": "Besorgungen",
    "289": "Intermittierende transurethrale Einmalkatheterisierung",
    "290": "Desinfektion",
    "291": "Einkaufen",
    "292": "Kleidung, austauschen und waschen der",
    "293": "Kochen",
    "294": "Krankenbett/-zimmers, Reinigung und Desinfektion des",
    "295": "Spülen des Geschirrs etc.",
    "296": "Wäsche, wechseln (austauschen) Reinigen der",
    "297": "Wohnung, Reinigung der",
    "298": "Anziehen von Kompressionsstrümpfen",
    "299": "Ausziehen von Kompressionsstrümpfen",
    "300": "Absaugen bei intubierten oder Tracheostoma-Patienten",
    "301": "Insulininjektion",
    "302": "Nase, Gabe von Salben und Tropfen bzw. Spülung",
    "303": "Klysma (Klistier: Darmeinlauf/Spülung)",
    "304": "Mikroklyst",
    "305": "Darmrohr legen",
    "306": "Dekubitusversorgung umfangreich",
    "307": "Augen- oder Ohrenspülung",
    "308": "Kompressionsverbände",
    "309": "Versorgung bei perkutaner endoskopischer Gastrostomie",
    "310": "Anleitung zur Pflege",
    "311": "Richten von Injektionen",
    "312": "Richten von Medikamenten (Dosimed)",
    "313": "Versorgung eines suprapubischen Katheters",
    "314": "Blutzuckermessung BZ-Tagesprofil (mindestens 3 Werte)",
    "315": "Digitale Enddarmausräumung",
    "316": "Mischung mehrerer Infusionen bei parenteralem Zugang",
    "317": "Erstbesuch",
    "318": "Orthesen, Anlegen/Ablegen von",
    "319": "Venenkatheter, Pflege des zentralen",
    "320": "Krankenbeobachtung, spezielle",
    "321": "Palliative Behandlungspflege",
    "322": "Wundverbände, Anlegen und Wechseln von",
    "323": "Stützende und stabilisierende Verbände, Anlegen von",
    "324": "Injektion, s.c.",
    "325": "Injektion, i.m.",
    "326": "Infusion, i.V. - zur parenteralen Ernährung",
    "327": "Infusion, i.V. - zur Flüssigkeitssubstitution",
    "328": "Dekubitusbehandlung Grad II",
    "329": "Dekubitusbehandlung Grad III",
    "330": "Dekubitusbehandlung Grad IV",
    "331": "Anleitung zur Blutdruckmessung",
    "332": "Anleitung zum Einlauf",
    "333": "Anleitung zur Inhalation",
    "334": "Anleitung zur s.c. Injektion – Insulin",
    "335": "Anleitung zur s.c. Injektion – sonstige Medikamente",
    "336": "Anleitung zur Injektion, Richten von",
    "337": "Anleitung zum Anlegen eines Urinals",
    "338": "Anleitung zur Medikamentengabe",
    "339": "Anleitung zum Augentropfen",
    "340": "Anleitung zum Ohren/Augentropfen",
    "341": "Anleitung zur Behandlungspflege (Leistungsgruppe 1)",
    "342": "Anleitung zur Behandlungspflege (Leistungsgruppe 2)",
    "343": "Anleitung zur Behandlungspflege (Leistungsgruppe 3)",
    "344": "Anleitung zur Behandlungspflege (Leistungsgruppe 4)",
    "345": "Anleitung zur Behandlungspflege (Leistungsgruppe 5)",
    "346": "Mitteilung an den Arzt",
    "347": "Anleitung zur Grundpflege (bis 30 Minuten)",
    "348": "Anleitung zur Grundpflege (bis zu 60 Minuten)",
    "349": "Anleitung zur Grundpflege (bis zu 2 Stunden)",
    "350": "Leistungsgruppe 1 – Einzelleistung 50 %",
    "351": "Leistungsgruppe 2 – Einzelleistung 50 %",
    "352": "Leistungsgruppe 3 – Einzelleistung 50 %",
    "353": "Leistungsgruppe 4 – Einzelleistung 50 %",
    "354": "Leistungsgruppe 1 – Einzelleistung 40 %",
    "355": "Leistungsgruppe 2 – Einzelleistung 40 %",
    "356": "Leistungsgruppe 3 – Einzelleistung 40 %",
    "357": "Leistungsgruppe 4 – Einzelleistung 40 %",
    "358": "Leistungsgruppe 1 – Einzelleistung 30 %",
    "359": "Leistungsgruppe 2 – Einzelleistung 30 %",
    "360": "Leistungsgruppe 3 – Einzelleistung 30 %",
    "361": "Leistungsgruppe 4 – Einzelleistung 30 %",
    "362": "Leistungsgruppe 1 – Einzelleistung 20 %",
    "363": "Leistungsgruppe 2 – Einzelleistung 20 %",
    "364": "Leistungsgruppe 3 – Einzelleistung 20 %",
    "365": "Leistungsgruppe 4 – Einzelleistung 20 %",
    "366": "Kombination von Anlegen/Wechseln v. Wund- u. Kompressionsverbänden",
    "367": "Richten von Medikamenten (Tagesdosette)",
    "368": "Medikamentengabe mit Sachleistungen der Pflegeversicherung (1 x täglich)",
    "369": "Medikamentengabe mit Sachleistungen der Pflegeversicherung (2 x täglich)",
    "370": "Medikamentengabe mit Sachleistungen der Pflegeversicherung (3 x täglich)",
    "371": "Einbringen eines transurethalen Einmalkatheters max. 5 Tage",
    "372": "Anleitung zur Blutzuckermessung",
    "373": "Anleitung zur Hilfe bei der Ernährung",
    "374": "Anleitung zur Hilfe bei Ausscheidungen",
    "375": "Anleitung zur Hilfe bei der Körperpflege",
    "376": "Anleitung zur Grundpflege insgesamt",
    "377": "Anleitung zum Anziehen von Kompressionsstrümpfen",
    "378": "Anleitung zum Ausziehen von Kompressionsstrümpfen",
    "379": "Ausscheidung, Hilfe bei",
    "380": "Insulininjektionen bei Zusammentreffen mit anderen Leistungen der Behandlungspflege",
    "381": "Insulingabe, einmal täglich",
    "382": "Insulingabe, zweimal täglich",
    "383": "Insulingabe, dreimal täglich",
    "384": "Drainagen in schwerwiegenden und aufwändigen Fällen",
    "385": "Anziehen von Kompressionsstrümpfen einschl. Versorgung von Ulcus cruris",
    "386": "Anlegen von Kompressionsverbänden einschl. Versorgung von Ulcus cruris",
    "387": "Abnehmen von Kompressionsverbänden",
    "388": "Medikamentengabe mittels Dosieraerosolen",
    "389": "Anleitung zur Behandlungspflege",
    "390": "Anleitung zum Absaugen",
    "391": "Anleitung zur Bronchialtoilette",
    "392": "Anleitung zur intensivierten Insulintherapie",
    "393": "Anleitung zur Dekubitusbehandlung",
    "394": "Anleitung zur Drainagen, überprüfen und versorgen",
    "395": "Anleitung zur Flüssigkeitsbilanzierung",
    "396": "Anleitung zur Instillation",
    "397": "Anleitung zum Auflegen von Kälteträgern",
    "398": "Anleitung zur Versorgung eines suprapubischen Katheters",
    "399": "Anleitung zum Legen und Wechseln einer Magensonde",
    "400": "Anleitung zum Richten von Medikamenten",
    "401": "Anleitung zur Einreibungen",
    "402": "Anleitung zum medizinischen Bad",
    "403": "Anleitung zur Behandlung des Mundes",
    "404": "Anleitung zur PEG, Versorgung einer perkutanen endoskopischen Gastrostomie",
    "405": "Anleitung zur Stomabehandlung",
    "406": "Anleitung zur Pflege des zentralen Venenkatheters",
    "407": "Anleitung zum Anlegen und Wechseln von Wundverbänden",
    "408": "Anleitung Kompressionsverbände",
    "409": "Anleitung zum An- und Ausziehen von Kompressionsstrümpfen/-hosen",
    "410": "Anleitung z. Anlegen v. stützenden u. stabilisierenden Verbänden",
    "411": "Dekubitusbehandlung 2. Stelle",
    "412": "Dekubitusbehandlung 3. Stelle",
    "413": "Dekubitusbehandlung 4. Stelle",
    "414": "Dekubitusbehandlung 5. Stelle",
    "415": "Subcutane Injektion 2. Präparat (andere Frequenz)",
    "416": "Subcutane Injektion 3. Präparat (andere Frequenz)",
    "417": "Insulininjektion 2. Präparat (andere Frequenz)",
    "418": "Intramuskuläre Injektion 2. Präparat (andere Frequenz)",
    "419": "Medikamentengabe 2. Frequenz",
    "420": "Medikamentengabe 3. Frequenz",
    "421": "Wundverbände 2. Stelle",
    "422": "Wundverbände 3. Stelle",
    "423": "Wundverbände 4. Stelle",
    "424": "Wundverbände 5. Stelle",
    "425": "Kompressionsverbände beide Beine",
    "426": "Anlegen Kompressionsverbände einschließlich Wundversorgung beider Beine",
    "427": "Anlegen Kompressionsverbände einschließlich Wundversorgung zweites Bein",
    "428": "Kompressionsverband zweites Bein",
    "429": "intensivierte Insulintherapie",
    "430": "Infusion i. V. nur Anhängen Ernährung",
    "431": "Infusion i. V. nur Abhängen Ernährung",
    "432": "Infusion i. V. Flüssigkeitssubstitution (Tagespauschale)",
    "433": "Infusion i. V. Ernährung (Tagespauschale)",
    "434": "Blutzuckerkontrolle bei Fortsetzung der intensivierten Insulintherapie",
    "435": "Trachealkanüle, Wechsel und Pflege",
    "436": "Deckelungsposition Verbände",
    "437": "Deckelungsposition Medikamente je Darreichungsform, Blutdruck, Flüssigkeitsbilanz",
    "438": "Deckelungsposition Blasenspülung, Drainagen, Instillation, Absaugen",
    "439": "An-/Abhängen von Infusionen",
    "440": "Hauswirtschaftliche Versorgung je Stunde, maximal 3 Stunden",
    "441": "Anleitung Injektion bis zu 2 je Besuch",
    "442": "Anleitung Injektion mehr als 2 je Besuch",
    "443": "Anleitung Kompressionsverband bei Ulcus",
    "444": "Anleitung Deckelungsposition Verbände",
    "445": "Anleitung zur Digitalen Enddarmausräumung",
    "446": "Anleitung Deckelungsposition Medikamente je Darreichungsform, Blutdruck, Flüssigkeitsbilanz",
    "447": "Anleitung Deckelungsposition Blasenspülung, Drainagen, Instillation, Absaugen",
    "448": "Anleitung zur Blasenspülung",
    "449": "Anleitung zum An-/Abhängen von Infusionen",
    "450": "Anleitung Infusionen, Überwachung von",
    "451": "Anleitung Grundpflege einschließlich Hauswirtschaft",
    "452": "Anleitung zur Katheterisierung",
    "453": "Hauswirtschaftliche Versorgung",
    "454": "Hauswirtschaftliche Versorgung (mehrfach täglich) in Verbindung mit Ernährung",
    "455": "Anleitung zur Bedienung und Überwachung des Beatmungsgerätes",
    "456": "Anleitung zur Dekubitusversorgung umfangreich",
    "457": "Anleitung zu Klysma",
    "458": "Anleitung zu Mikroklyst",
    "459": "Anleitung zu Injektion, i. m.",
    "460": "Anleitung zum Aufziehen von Insulin",
    "461": "Anleitung zur speziellen Krankenbeobachtung",
    "462": "Anleitung zu Ohren, Gabe von Salben und Tropfen",
    "463": "Anleitung zu Nase, Gabe von Salben und Tropfen bzw. Spülung",
    "464": "Anleitung zu Pflege und Wechsel der Trachealkanüle",
    "465": "Anleitung zur Kombination von Verbänden zur Wundversorgung und Kompressionsverbänden",
    "466": "2 Verbände je Hausbesuch",
    "467": "3 Verbände je Hausbesuch",
    "468": "4 Verbände je Hausbesuch",
    "469": "5 Verbände je Hausbesuch",
    "470": "2 Dekubitusbehandlungen je Hausbesuch",
    "471": "3 Dekubitusbehandlungen je Hausbesuch",
    "472": "4 Dekubitusbehandlungen je Hausbesuch",
    "473": "5 Dekubitusbehandlungen je Hausbesuch",
    "474": "2 Kompressionsverbände anlegen je Hausbesuch / Anlegen von Kompressionsverbänden 1. und 2. Körperstelle (getrennt in einem Einsatz)",
    "475": "2 Kompressionsverbände anlegen bei Ulcus cruris je Hausbesuch",
    "476": "Medikamentenabgabe mittels Salben",
    "477": "Medikamentenabgabe mittels Tropfen, Säfte, Tinkturen",
    "478": "Medikamentenabgabe mittels Zäpfchen",
    "479": "Medikamentenabgabe mittels Herz-, Schmerz-, Hormonpflaster",
    "480": "Anleitung Medikamentenabgabe mittels Salben",
    "481": "Anleitung Medikamentenabgabe mittels Tropfen, Säfte, Tinkturen",
    "482": "Anleitung Medikamentenabgabe mittels Zäpfchen",
    "483": "Anleitung Medikamentenabgabe mittels Herz-, Schmerz-, Hormonpflaster",
    "484": "Anleitung Medikamentenabgabe mittels Dosieraerosol",
    "485": "Anlegen und Wechseln von Wundverbänden phasengerechte Versorgung 1. Stelle",
    "486": "Anlegen und Wechseln von Wundverbänden phasengerechte Versorgung 2. Stelle",
    "487": "Anlegen und Wechseln von Wundverbänden phasengerechte Versorgung 3. Stelle",
    "488": "Anlegen und Wechseln von Wundverbänden phasengerechte Versorgung 4. Stelle",
    "489": "Anlegen und Wechseln von Wundverbänden aufwendige Wundversorgung/phasengerecht 1. Stelle",
    "490": "Anlegen und Wechseln von Wundverbänden aufwendige Wundversorgung/phasengerecht 2. Stelle",
    "491": "Anlegen und Wechseln von Wundverbänden aufwendige Wundversorgung/phasengerecht 3. Stelle",
    "492": "Anlegen und Wechseln von Wundverbänden aufwendige Wundversorgung/phasengerecht 4. Stelle",
    "493": "Dekubitusbehandlung phasengerechte Versorgung 1. Stelle",
    "494": "Dekubitusbehandlung phasengerechte Versorgung 2. Stelle",
    "495": "Dekubitusbehandlung phasengerechte Versorgung 3. Stelle",
    "496": "Dekubitusbehandlung phasengerechte Versorgung 4. Stelle",
    "497": "Dekubitusbehandlung aufwendige Versorgung 1. Stelle",
    "498": "Dekubitusbehandlung aufwendige Versorgung 2. Stelle",
    "499": "Dekubitusbehandlung aufwendige Versorgung 3. Stelle",
    "500": "Dekubitusbehandlung aufwendige Versorgung 4. Stelle",
    "501": "Dekubitusbehandlung, mehrere Grad 2",
    "502": "Dekubitusbehandlung, mehrere Grad 3",
    "503": "Dekubitusbehandlung, mehrere Grad 4",
    "504": "Ersteinsatz nach PEG-Erstanlage",
    "505": "Ersteinsatz nach SPK-Erstanlage",
    "506": "Grundpflege (Körperpflege / Ernährung / Ausscheidungen) bis 30 Minuten",
    "507": "Grundpflege (Körperpflege / Ernährung / Ausscheidungen) bis 60 Minuten",
    "508": "Flüssigkeitsbilanzierung in Zusammenhang m. anderen Leistungen",
    "509": "Dekubitusbehandlung, bis zu zwei Dekubiti Grad 2",
    "510": "Dekubitusbehandlung, mehr als zwei Dekubiti Grad 2",
    "511": "Schulung zur Einmalkatheterisierung, transurethral",
    "512": "Medizinische Behandlung des Mundes",
    "513": "Psychiatrische Häusliche Krankenpflege",
    "514": "Erarbeiten der Pflegeakzeptanz",
    "515": "Bewältigung / Intervention von Krisensituationen",
    "516": "Entwickeln kompensatorischer Hilfen bei krankheitsbedingter Einschränkung",
    "517": "Medigabe bei amb. psych. Krankenpflege als alleinige Leistung",
    "518": "Richten von Medikamenten (Wochendosimed)",
    "519": "Infusionen, einzeln",
    "520": "Anleitung zur Behandlungspflege (Leistungsgruppe 7)",
    "521": "Port-a-cath Versorgung anschließen",
    "522": "Port-a-cath Versorgung abschließen",
    "523": "Port-a-cath Spülung",
    "524": "Überprüfung und Versorgung von Drainagen",
    "525": "Anlegen eines Kompressionsverbandes",
    "526": "Einlauf/Klistier/Klysma/Darmspülung sowie digitale Enddarmausräumung",
    "527": "Katheterisierung der Harnblase",
    "528": "Sonstige Leistungen als Einzelfallentscheidung",
    "529": "Augen, Gabe von Salben und Tropfen bei postoperativen Zuständen",
    "530": "Wundverbände 6. Stelle",
    "531": "Wundverbände 7. Stelle",
    "532": "Wundverbände 8. Stelle",
    "533": "Wundverbände 9. Stelle",
    "534": "Wundverbände 10. Stelle",
    "535": "Dekubitusbehandlung 6. Stelle",
    "536": "Dekubitusbehandlung 7. Stelle",
    "537": "Dekubitusbehandlung 8. Stelle",
    "538": "Dekubitusbehandlung 9. Stelle",
    "539": "Dekubitusbehandlung 10. Stelle",
    "540": "Häusliche psychiatrische Krankenpflege 2. Woche",
    "541": "Häusliche psychiatrische Krankenpflege 3. Woche",
    "542": "Häusliche psychiatrische Krankenpflege 4. Woche",
    "543": "Häusliche psychiatrische Krankenpflege 5. Woche",
    "544": "Häusliche psychiatrische Krankenpflege 6. Woche",
    "545": "Häusliche psychiatrische Krankenpflege 7. Woche",
    "546": "Häusliche psychiatrische Krankenpflege 8. Woche",
    "547": "Häusliche psychiatrische Krankenpflege 9. Woche",
    "548": "Häusliche psychiatrische Krankenpflege 10. Woche",
    "549": "Häusliche psychiatrische Krankenpflege 11. Woche",
    "550": "Häusliche psychiatrische Krankenpflege 12. Woche",
    "551": "Häusliche psychiatrische Krankenpflege 13. Woche",
    "552": "Häusliche psychiatrische Krankenpflege 14. Woche",
    "553": "Häusliche psychiatrische Krankenpflege 15. Woche",
    "554": "Häusliche psychiatrische Krankenpflege 16. Woche",
    "555": "Hauswirtschaftliche Versorgung bis 60 Minuten",
    "556": "Hauswirtschaftliche Versorgung bis 120 Minuten",
    "557": "Versorgung eines oder mehrerer Dekubiti Stadium 3 und/oder 4",
    "558": "Einmalzahlung (Erfolgszuschlag) bei Entwöhnung vom Beatmungsgerät",
    "559": "Wundreinigungsbad als Zulage bei Anlegen und Wechsel von Wundverbänden",
    "560": "Anleitung zur kleinen Behandlungspflege - max. 10 Einsätze",
    "561": "Anleitung zur mittleren Behandlungspauschale - max. 10 Einsätze",
    "562": "Anleitung zur großen Behandlungspauschale - max. 10 Einsätze",
    "563": "Anleitung zu Injektionen, intramuskulär und subcutan",
    "564": "Anleitung zu Einlauf / Klistier / Klysma / Darmspiegelung sowie digitaler Enddarmausräumung",
    "565": "Anleitung zur Intermittierende transurethrale Einmalkatheterisierung (ITEK)",
    "566": "Versenden von Pflegedokumentationen an die Krankenkasse",
    "567": "Intensivpflege",
    "568": "Medikamentengabe spezielle",
    "569": "Wundverbände spezielle",
    "570": "Grundpflege (Körperpflege / Ernährung / Ausscheidungen) bis 15 Minuten",
    "571": "Grundpflege (Körperpflege / Ernährung / Ausscheidungen) bis 45 Minuten",
    "572": "Hauswirtschaftliche Versorgung bis 15 Minuten",
    "573": "Hauswirtschaftliche Versorgung bis 45 Minuten",
    "574": "Grundpflege (Körperpflege/Ernährung/Ausscheidungen) bis 120 Minuten",
    "575": "Anlegen von Kompressionsverbänden 3. und 4. Körperstelle getrennt in einem Einsatz",
    "576": "Abnehmen von Kompressionsverbänden 1. Körperstelle (zeitgleich mit Anlegen)",
    "577": "Abnehmen von Kompressionsverbänden 3. und 4. Körperstelle (zeitgleich mit Anlegen)",
    "578": "Anlegen von Kompressionsverbänden 1. Körperstelle",
    "579": "Abnehmen von Kompressionsverbänden 2. Körperstelle (zeitgleich mit Anlegen)",
    "580": "Abnehmen von Kompressionsverbänden 1. Körperstelle (zeitlich getrennt vom Anlegen)",
    "581": "Abnehmen von Kompressionsverbänden 2. Körperstelle (zeitlich getrennt vom Anlegen)",
    "582": "Kompressionstherapie einschl. Versorgung Ulcus cruris, rechtes Bein",
    "583": "Kompressionstherapie einschl. Versorgung Ulcus cruris, linkes Bein",
    "584": "Anlegen eines Kompressionsverbandes, rechtes Bein",
    "585": "Anlegen eines Kompressionsverbandes, linkes Bein",
    "586": "Anleitung zum Anlegen eines Kompressionsverbandes",
    "587": "Abnehmen von Kompressionsverband rechtes Bein",
    "588": "Abnehmen von Kompressionsverband linkes Bein",
    "589": "Abnehmen von Kompressionsverbänden Anleitung",
    "590": "Abnehmen von Kompressionsverbänden Erfolgspauschale",
    "591": "s.c. Infusion",
    "200": "Legen und Anhängen einer s.c.-Infusion",
    "598": "Abnehmen einer s.c.-Infusion",
    "599": "Anleitung beim Legen und Anhängen einer s.c.-Infusion",
    "656": "Anleitung beim Abnehmen einer s.c.-Infusion",
    "592": "Abnehmen Kompressionsverbände beide Beine",
    "593": "Anleitung zum Abwickeln eines Kompressionsverbandes",
    "594": "Anleitung zum Abwickeln von zwei Kompressionsverbänden",
    "595": "Deckelung aus Blutdruckmessung und Flüssigkeitsbilanzierung (6aMAX)",
    "596": "Anleitung: Deckelung aus Blutdruckmessung und Flüssigkeitsbilanzierung (6aMAX)",
    "597": "Anlegen von stützenden/stabilisierenden Verbänden beide Beine",
    "753": "Behandlungspflege Intensivpflege Einzelversorgung - Stunden",
    "754": "Behandlungspflege Intensivpflege Einzelversorgung - Minuten",
    "755": "Betreuungszeiten Intensivpflege Einzelversorgung - Stunden",
    "756": "Betreuungszeiten Intensivpflege Einzelversorgung - Minuten",
    "757": "Behandlungspflege und Betreuungszeit Intensivpflege Einzelversorgung - Stunden",
    "758": "Behandlungspflege und Betreuungszeit Intensivpflege Einzelversorgung - Minuten",
    "759": "Behandlungspflege und Betreuungszeit Intensivpflege Einzelversorgung - 1. bis 2. Stunde",
    "760": "Behandlungspflege und Betreuungszeit Intensivpflege Einzelversorgung - Minuten (1. bis 2. Stunde)",
    "761": "Behandlungspflege und Betreuungszeit Intensivpflege Einzelversorgung - 3. bis 4. Stunde",
    "762": "Behandlungspflege und Betreuungszeit Intensivpflege Einzelversorgung - Minuten (3. bis 4. Stunde)",
    "763": "Behandlungspflege und Betreuungszeit Intensivpflege Einzelversorgung - 5. bis 24. Stunde",
    "764": "Behandlungspflege und Betreuungszeit Intensivpflege Einzelversorgung - Minuten (5. bis 24. Stunde)",
    "765": "Höchstbetrag Intensivpflege je Einsatz",
    "766": "Höchstbetrag Intensivpflege je Tag",
    "767": "Höchstbetrag Intensivpflege je Tag und Nacht",
    "768": "Höchstbetrag Intensivpflege je Monat",
    "769": "Behandlungspflege Intensivpflege WG 1 - Stunden",
    "770": "Behandlungspflege Intensivpflege WG 1 - Minuten",
    "771": "Betreuungszeiten Intensivpflege WG 1 - Stunden",
    "772": "Betreuungszeiten Intensivpflege WG 1 - Minuten",
    "773": "Behandlungspflege Intensivpflege WG 2 - Stunden",
    "774": "Behandlungspflege Intensivpflege WG 2 - Minuten",
    "775": "Betreuungszeiten Intensivpflege WG 2 - Stunden",
    "776": "Betreuungszeiten Intensivpflege WG 2 - Minuten",
    "777": "Behandlungspflege Intensivpflege WG 3 - Stunden",
    "778": "Behandlungspflege Intensivpflege WG 3 - Minuten",
    "779": "Betreuungszeiten Intensivpflege WG 3 - Stunden",
    "780": "Betreuungszeiten Intensivpflege WG 3 - Minuten",
    "781": "Behandlungspflege Intensivpflege WG 4 - Stunden",
    "782": "Behandlungspflege Intensivpflege WG 4 - Minuten",
    "783": "Betreuungszeiten Intensivpflege WG 4 - Stunden",
    "784": "Betreuungszeiten Intensivpflege WG 4 - Minuten",
    "785": "Behandlungspflege Intensivpflege WG 5 - Stunden",
    "786": "Behandlungspflege Intensivpflege WG 5 - Minuten",
    "787": "Betreuungszeiten Intensivpflege WG 5 - Stunden",
    "788": "Betreuungszeiten Intensivpflege WG 5 - Minuten",
    "793": "Behandlungspflege Intensivpflege WG 6 - Stunde",
    "794": "Behandlungspflege Intensivpflege WG 6 - Minute",
    "795": "Betreuungszeiten Intensivpflege WG 6 - Stunde",
    "796": "Betreuungszeiten Intensivpflege WG 6 - Minute",
    "797": "Behandlungspflege Intensivpflege WG 7 - Stunde",
    "798": "Behandlungspflege Intensivpflege WG 7 - Minute",
    "799": "Betreuungszeiten Intensivpflege WG 7 - Stunde",
    "800": "Betreuungszeiten Intensivpflege WG 7 - Minute",
    "119": "Medikamentengabe bei gleichzeitigem Einsatz nach SGB XI",
    "169": "Medikamentengabe als Einreibung bei gleichzeitigem Einsatz nach SGB XI",
    "657": "Medikamentengabe zur Behandlung des Mundes bei gleichzeitigem Einsatz nach SGB XI",
    "658": "Medikamentengabe zur Behandlung des Auges bei gleichzeitigem Einsatz nach SGB XI",
    "659": "Medikamentengabe mittels Pflaster bei gleichzeitigem Einsatz nach SGB XI",
    "789": "Medikamentengabe mittels medizinischem Bad bei gleichzeitigem Einsatz nach SGB XI",
    "899": "Anleitung zum Richten von Medikamenten in einer Wochendosierbox",
    "900": "Richten von Medikamenten in einer Tagesdosierbox beim gleichzeitigen Einsatz nach SGB XI",
    "902": "Wunde Grad A (einfache Wundversorgung)",
    "903": "Anleitung Wunde Grad A (einfache Wundversorgung)",
    "904": "Wunde Grad B (klassische Wundversorgung)",
    "905": "Anleitung Wunde Grad B (klassische Wundversorgung)",
    "906": "Wunde Grad C (aufwändige Wundversorgung)",
    "907": "Anleitung Wunde Grad C (aufwändige Wundversorgung)",
    "908": "Abnehmen eines Kompressionsverbandes (je Extremität)",
    "918": "MRSA begleitende Maßnahmen",
    "919": "MRSA Medikamentengabe + begleitende Maßnahmen",
    "923": "MRSA-Medikamentengabe",
    "927": "Medizinisches Teilbad (im Bereich der Medikamentengabe)",
    "928": "MRSA Dekontamination von Haut und Haaren mit antiseptischen Substanzen (dermatologische Behandlung/Bad)",
    "929": "Wundversorgung, bis zu zwei Stellen",
    "930": "2 Wundversorgung, mehr als zwei Stellen",
    "934": "Behandlungspflege Intensivpflege Einzelversorgung Tag - Stunden",
    "935": "Betreuungszeiten Intensivpflege Einzelversorgung Tag - Stunden",
    "936": "Behandlungspflege Intensivpflege Einzelversorgung Tag – Minuten",
    "937": "Betreuungszeiten Intensivpflege Einzelversorgung Tag – Minuten",
    "938": "Behandlungspflege Intensivpflege Einzelversorgung Nacht – Stunden",
    "939": "Betreuungszeiten Intensivpflege Einzelversorgung Nacht - Stunden",
    "940": "Behandlungspflege Intensivpflege Einzelversorgung Nacht – Minuten",
    "941": "Betreuungszeiten Intensivpflege Einzelversorgung Nacht – Minuten",
    "942": "Behandlungspflege und Betreuungszeit Intensivpflege Einzelversorgung Tag – Stunden",
    "943": "Behandlungspflege und Betreuungszeit Intensivpflege Einzelversorgung Tag – Minuten",
    "944": "Behandlungspflege und Betreuungszeit Intensivpflege Einzelversorgung Nacht – Stunden",
    "945": "Behandlungspflege und Betreuungszeit Intensivpflege Einzelversorgung Nacht – Minuten",
    "946": "Behandlungspflege Intensivpflege WG Tag - Stunden",
    "947": "Betreuungszeiten Intensivpflege WG Tag - Stunden",
    "948": "Behandlungspflege Intensivpflege WG Tag – Minuten",
    "949": "Betreuungszeiten Intensivpflege WG Tag – Minuten",
    "950": "Behandlungspflege Intensivpflege WG Nacht – Stunden",
    "951": "Betreuungszeiten Intensivpflege WG Nacht - Stunden",
    "952": "Behandlungspflege Intensivpflege WG Nacht – Minuten",
    "953": "Betreuungszeiten Intensivpflege WG Nacht – Minuten",
    "954": "Behandlungspflege und Betreuungszeit Intensivpflege WG Tag – Stunden",
    "955": "Behandlungspflege und Betreuungszeit Intensivpflege WG Tag – Minuten",
    "956": "Behandlungspflege und Betreuungszeit Intensivpflege WG Nacht – Stunden",
    "957": "Behandlungspflege und Betreuungszeit Intensivpflege WG Nacht – Minuten",
    "958": "Behandlungspflege und Betreuungszeit Intensivpflege Tag – Pauschale",
    "959": "Behandlungspflege und Betreuungszeit Intensivpflege Nacht – Pauschale",
    "960": "Behandlungspflege Intensivpflege Einzelversorgung Sonstige 1 - Stunden",
    "961": "Betreuungszeiten Intensivpflege Einzelversorgung Sonstige 1 - Stunden",
    "962": "Behandlungspflege Intensivpflege Einzelversorgung Sonstige 1 – Minuten",
    "963": "Betreuungszeiten Intensivpflege Einzelversorgung Sonstige 1 – Minuten",
    "964": "Behandlungspflege Intensivpflege Einzelversorgung Sonstige 2 - Stunden",
    "965": "Betreuungszeiten Intensivpflege Einzelversorgung Sonstige 2 - Stunden",
    "966": "Behandlungspflege Intensivpflege Einzelversorgung Sonstige 2 – Minuten",
    "967": "Betreuungszeiten Intensivpflege Einzelversorgung Sonstige 2 – Minuten",
    "968": "Behandlungspflege Intensivpflege Einzelversorgung Sonstige 3 - Stunden",
    "969": "Betreuungszeiten Intensivpflege Einzelversorgung Sonstige 3 - Stunden",
    "970": "Behandlungspflege Intensivpflege Einzelversorgung Sonstige 3 – Minuten",
    "971": "Betreuungszeiten Intensivpflege Einzelversorgung Sonstige 3 – Minuten",
    "972": "Behandlungspflege und Betreuungszeit Intensivpflege Einzelversorgung Sonstige 1 – Stunden",
    "973": "Behandlungspflege und Betreuungszeit Intensivpflege Einzelversorgung Sonstige 1 – Minuten",
    "974": "Behandlungspflege und Betreuungszeit Intensivpflege Einzelversorgung Sonstige 2 – Stunden",
    "975": "Behandlungspflege und Betreuungszeit Intensivpflege Einzelversorgung Sonstige 2 – Minuten",
    "976": "Behandlungspflege und Betreuungszeit Intensivpflege Einzelversorgung Sonstige 3 – Stunden",
    "977": "Behandlungspflege und Betreuungszeit Intensivpflege Einzelversorgung Sonstige 3 – Minuten",
    "981": "Zusammentreffen von s. c. Infusion abnehmen und Medikamentengabe",
    "982": "Zusammentreffen von Abnehmen eines Kompressionsverbandes und Medikamentengabe",
    "983": "Zusammentreffen von Medikamentengabe und Einreibungen",
    "984": "Kompressionsstrümpfe anziehen ab Klasse II an einer Extremität",
    "985": "Kompressionsstrümpfe anziehen ab Klasse II an zwei Extremitäten",
    "986": "Kompressionsstrümpfe anziehen ab Klasse II an drei Extremitäten",
    "987": "Kompressionsstrümpfe anziehen ab Klasse II an vier Extremitäten",
    "988": "Kompressionsstrümpfe ausziehen ab Klasse II an einer Extremität",
    "989": "Kompressionsstrümpfe ausziehen ab Klasse II an zwei Extremitäten",
    "990": "Kompressionsstrümpfe ausziehen ab Klasse II an drei Extremitäten",
    "991": "Kompressionsstrümpfe ausziehen ab Klasse II an vier Extremitäten",
    "992": "Kompressionsverband anlegen oder Wechseln - nicht abwickeln - an 3 Extremitäten",
    "993": "Kompressionsverband anlegen oder Wechseln - nicht abwickeln - an 4 Extremitäten",
    "994": "Abwickeln von Kompressionsverbänden (einschließlich Aufwickeln des Verbandes auf eine Rolle) an 3 Extremitäten",
    "995": "Abwickeln von Kompressionsverbänden (einschließlich Aufwickeln des Verbandes auf eine Rolle) an 4 Extremitäten",
    "996": "Anleitung bei der Grundpflege in der Häuslichkeit",
    "997": "Anleitung bei s.c.- / i.m.-Injektionen bei Verwendung von Fertigspritzen (bis zu 2 Injektionen pro Besuch)",
    "998": "Anleitung bei 2 Wundverbänden anlegen oder wechseln",
    "999": "Anleitung bei 3 Wundverbänden anlegen oder wechseln",
    "A01": "Anleitung bei Dekubitusbehandlung ab Grad II bei 2 Dekubiti",
    "A02": "Anleitung bei Dekubitusbehandlung ab Grad II bei 3 Dekubit",
    "A03": "Anleitung bei Kompressionsstrümpfe anziehen ab Klasse II an zwei Extremitäten",
    "A04": "Anleitung bei Kompressionsstrümpfe anziehen ab Klasse II an drei Extremitäten",
    "A05": "Anleitung bei Kompressionsstrümpfe anziehen ab Klasse II an vier Extremitäten",
    "A06": "Anleitung bei Kompressionsstrümpfe ausziehen ab Klasse II an zwei Extremitäten",
    "A07": "Anleitung bei Kompressionsstrümpfe ausziehen ab Klasse II an drei Extremitäten",
    "A08": "Anleitung bei Kompressionsstrümpfe ausziehen ab Klasse II an vier Extremitäten",
    "A09": "Anleitung bei Kompressionsverband anlegen oder Wechseln - nicht abwickeln - an 2 Extremitäten",
    "A10": "Anleitung bei Kompressionsverband anlegen oder Wechseln - nicht abwickeln - an 3 Extremitäten",
    "A11": "Anleitung bei Kompressionsverband anlegen oder Wechseln - nicht abwickeln - an 4 Extremitäten",
    "A12": "Anleitung bei Kompression bei Ulcus cruris-Behandlung (einschl. Wundreinigung, Spülung, Versorgung mit Medikamenten; ohne med.Bad gemäß Pos. Nr. 6a10) an 2 Beinen",
    "A13": "Anleitung beim Abwickeln von Kompressionsverbänden (einschließlich Aufwickeln des Verbandes auf eine Rolle)",
    "A14": "Anleitung beim Abwickeln von Kompressionsverbänden (einschließlich Aufwickeln des Verbandes auf eine Rolle) an 2 Extremitäten",
    "A15": "Anleitung beim Abwickeln von Kompressionsverbänden (einschließlich Aufwickeln des Verbandes auf eine Rolle) an 3 Extremitäten",
    "A16": "Anleitung beim Abwickeln von Kompressionsverbänden (einschließlich Aufwickeln des Verbandes auf eine Rolle) an 4 Extremitäten",
    "A17": "Anleitung bei Blutdruckmessung und Flüssigkeitsbilanzierung bei einem Hausbesuch (6a6+6a7)",
    "A18": "Anleitung bei MRSA-Eradikationstherapie (MRSA-Sanierung) einschließlich aller damit zusammenhängenden Leistungen",
    "A86": "Kontinuierliche Medikamentengabe über Schmerzpumpe im Rahmen der Symptomkontrolle (24a)",
    "A87": "Wundversorgung als Einzelfallentscheidung im Rahmen der Symptomkontrolle (24a)",
    "A88": "Wundversorgung als sonstige Einzelfallentscheidung",
    "A92": "Hebe-/Senkeinlauf",
    "A95": "MRSA Mund- und Rachenspülung mit einer antiseptischen Lösung",
    "A96": "MRSA Applikation einer antibakteriellen Nasensalbe oder eines antiseptischen Nasengels",
    "A97": "MRSA Begleitende Maßnahmen bei Versicherten ohne Anspruch auf Leistungen nach dem SGB XI",
    "A98": "Anleitung bei Hebe-/Senkeinlauf",
    "A99": "Klistier/Klysma (bitte ohne Hinweis auf Einlauf)",
    "B01": "Anleitung bei Klistier/Klysma (bitte ohne Hinweis auf Einlauf)",
    "B03": "Anlegen Kompressionsstrumpf rechter Arm",
    "B04": "Anlegen Kompressionsstrumpf linker Arm",
    "B05": "Abnehmen Kompressionsstrumpf rechter Arm",
    "B06": "Abnehmen Kompressionsstrumpf linker Arm",
    "B07": "Anleitung zum Anlegen eines Kompressionsstrumpfes am Arm",
    "B08": "Anleitung zum Abnehmen eines Kompressionsstrumpfes am Arm",
    "B09": "Intensivpflege – Versicherte mit Anspruch auf Leistungen bei häuslicher Pflege gemäß §§ 36, 38 SGB XI",
    "B10": "Intensivpflege – Versicherte ohne Anspruch auf Leistungen bei häuslicher Pflege gemäß §§ 36, 38 SGB XI",
    "B11": "An- und ablegen bei Maskenbeatmung",
    "B19": "An- und Ausziehen von Kompressionsstrümpfen Druckklasse 1",
    "B22": "Ausziehen von Kompressionsstrümpfen der Klasse I",
    "B28": "Kompressionsstrümpfe anziehen ab Klasse I an einer Extremität",
    "B29": "Kompressionsstrümpfe anziehen ab Klasse I an zwei Extremitäten",
    "B30": "Kompressionsstrümpfe anziehen ab Klasse I an drei Extremitäten",
    "B31": "Kompressionsstrümpfe anziehen ab Klasse I an vier Extremitäten",
    "B32": "Kompressionsstrümpfe ausziehen ab Klasse I an einer Extremität",
    "B33": "Kompressionsstrümpfe ausziehen ab Klasse I an zwei Extremitäten",
    "B34": "Kompressionsstrümpfe ausziehen ab Klasse I an drei Extremitäten",
    "B35": "Kompressionsstrümpfe ausziehen ab Klasse I an vier Extremitäten",
    "B36": "Anleitung bei Kompressionsstrümpfe anziehen ab Klasse I an einer Extremität",
    "B37": "Anleitung bei Kompressionsstrümpfe anziehen ab Klasse I an zwei Extremitäten",
    "B38": "Anleitung bei Kompressionsstrümpfe anziehen ab Klasse I an drei Extremitäten",
    "B39": "Anleitung bei Kompressionsstrümpfe anziehen ab Klasse I an vier Extremitäten",
    "B40": "Anleitung bei Kompressionsstrümpfe ausziehen ab Klasse I an einer Extremität",
    "B41": "Anleitung bei Kompressionsstrümpfe ausziehen ab Klasse I an zwei Extremitäten",
    "B42": "Anleitung bei Kompressionsstrümpfe ausziehen ab Klasse I an drei Extremitäten",
    "B43": "Anleitung bei Kompressionsstrümpfe ausziehen ab Klasse I an vier Extremitäten",
    "B46": "Wundversorgung: Vergütung für die Erstbehandlung mit weitergehenden Inhalten",
    "B47": "Wundversorgung: Vergütung für weitere Behandlungen",
    "B48": "Trachealkanüle, Wechsel und Pflege mit Absaugen",
    "B49": "Korrektur des bereits gerichteten Wochendispensers aufgrund ärztlich verordneter Medikamentenänderung",
    "B72": "Stomabehandlung",
    "B79": "Positionswechsel zur Dekubitusbehandlung (Nr. 12)",
    "B80": "Wundversorgung einer akuten Wunde (Nr. 31)",
    "B81": "Wundversorgung einer chronischen und schwer heilenden Wunde (Nr. 31a)",
    "B82": "Ablegen von stützenden und stabilisierenden Verbänden (Nr. 31c)",
    "B83": "Positionswechsel zur Dekubitusbehandlung Grad 1",
    "B84": "Positionswechsel zur Dekubitusbehandlung ab Grad 2",
    "B85": "Anleitung bei Positionswechsel zur Dekubitusbehandlung",
    "B86": "Anleitung bei Positionswechsel zur Dekubitusbehandlung Grad 1",
    "B87": "Anleitung bei Positionswechsel zur Dekubitusbehandlung ab Grad 2",
    "B88": "Anleitung zum Ablegen von stützenden und stabilisierenden Verbänden (Nr. 31c)",
    "C02": "An- oder Ausziehen von ärztlich verordneten Kompressionsstrümpfen/- strumpfhosen der Kompressionsklassen I bis IV (Nr. 31b)",
    "C03": "Anleitung zum Anziehen von Kompressionsstrümpfen der Klasse I",
    "C04": "Anleitung zum Anziehen von Kompressionsstrümpfen ab Klasse II",
    "C13": "Anlegen von Bandagen und Orthesen (Nr. 31d)",
    "C14": "Ablegen von Bandagen und Orthesen (Nr. 31d)",
    "C15": "An- und Ablegen von Bandagen und Orthesen (Nr. 31d)",
    "C16": "Anleitung zum Anlegen von Bandagen und Orthesen (Nr. 31d)",
    "C17": "Anleitung zum Ablegen von Bandagen und Orthesen (Nr. 31d)",
    "C18": "Anleitung zum An- und Ablegen von Bandagen und Orthesen (Nr. 31d)",
    "C24": "Ermittlung und Bewertung des interstitiellen Glukosegehaltes mittels Testgerät (Nr. 11a)",
    "C25": "Sensorwechsel bei Bedarf (Nr. 11a)",
    "C26": "Kalibrierung bei Bedarf (Nr. 11a)",
    "C27": "Sensorwechsel bei Bedarf inklusive Kalibrierung (Nr. 11a)",
    "C28": "Anleitung zur Ermittlung und Bewertung des interstitiellen Glukosegehaltes mittels Testgerät (Nr. 11a)",
    "C29": "Anleitung zum Sensorwechsel bei Bedarf (Nr. 11a)",
    "C30": "Anleitung zur Kalibrierung bei Bedarf (Nr. 11a)",
    "C31": "Anleitung zum Sensorwechsel bei Bedarf inklusive Kalibrierung (Nr. 11a)",
    "C32": "Ermittlung und Bewertung des interstitiellen Glukosegehaltes (Nr. 11a) in Verbindung mit anderen Leistungen",
    "C33": "Anleitung zur Ermittlung und Bewertung des interstitiellen Glukosegehaltes (Nr. 11a) in Verbindung mit anderen Leistungen",
    "C35": "Interstitielle Glukosemessung (Nr. 11a)",
    "C62": "Anleitung zur Interstitiellen Glukosemessung (Nr. 11a)",
    "C70": "Ablegen von ärztlich verordneten Bandagen u. Orthesen (31d)",
    "C71": "Anlegen von ärztlich verordneten Bandagen u. Orthesen (31d)",
    "C72": "Ablegen von stützenden oder stabilisierenden Verbänden (31c)",
    "C73": "Positionswechsel zur Dekubitusbehandlung (12)",
    "C74": "Interstitielle Glukosemessung (11a) (Sensorwechsel bei Bedarf)",
    "C75": "Interstitielle Glukosemessung (11a) (Kalibrierung bei Bedarf)",
    "C76": "Interstitielle Glukosemessung (11a) (Kalibrierung und Sensorwechsel bei Bedarf)",
    "C77": "Anleitungserfolg bei Ablegen von ärztlich verordneten Bandagen u. Orthesen (31d)",
    "C78": "Anleitungserfolg bei Anlegen von ärztlich verordneten Bandagen u. Orthesen (31d)",
    "C79": "Anleitungserfolg bei Ablegen von stützenden oder stabilisierenden Verbänden (31c)",
    "C80": "Anleitungserfolg bei Positionswechsel zur Dekubitusbehandlung (12)",
    "C81": "Anleitungserfolg bei Interstitielle Glukosemessung (11a) (Sensorwechsel bei Bedarf)",
    "C82": "Anleitungserfolg bei Interstitielle Glukosemessung (11a) (Kalibrierung bei Bedarf)",
    "C83": "Anleitungserfolg bei Interstitielle Glukosemessung (11a) (Kalibrierung und Sensorwechsel bei Bedarf)",
}
export type EinzelleistungenVerguetungsArtSchluessel = keyof typeof einzelleistungenVerguetungsArtSchluessel

/** Zuschläge / Abzüge */
export const zuschlaegeAbzuegeVerguetungsArtSchluessel = {
    "600": "Hausbesuch von 20.00 Uhr bis 6.00 Uhr",
    "601": "Hausbesuch an Sonn- und Feiertagen",
    "602": "Hausbesuch bei Kindern (0-6 Jahre)",
    "603": "Hausbesuch zu ungünstigen Zeiten",
    "604": "für Kinderkrankenpflege",
    "605": "für Tag- und Nachtwache",
    "606": "für Samstag",
    "607": "für Sonn- und Feiertag",
    "608": "Hausbesuch an Sams-, Sonn- und Feiertagen mit Sachleistungen der Pflegeversicherung",
    "609": "Hausbesuch bei Nacht mit Sachleistungen der Pflegeversicherung",
    "610": "Hausbesuch mehrerer Patienten an Sams-, Sonn- und Feiertagen mit Sachleistungen der Pflegeversicherung",
    "611": "Hausbesuch mehrerer Patienten bei Nacht mit Sachleistungen der Pflegeversicherung",
    "612": "Hausbesuch zu ungünstigen Zeiten mit Sachleistungen der Pflegeversicherung",
    "613": "Zuschlag zur Grundpflege",
    "614": "Erfolgszuschlag bei Anleitung zur Behandlungspflege",
    "615": "Erfolgszuschlag für Anleitung bei Grundpflege allgemein",
    "616": "Erfolgszuschlag für Anleitung zur Bedienung/Überwachung eines Beatmungsgerätes",
    "617": "Erfolgszuschlag für Anleitung zur Blasenspülung",
    "618": "Erfolgszuschlag für Anleitung zur Blutdruckmessung",
    "619": "Erfolgszuschlag für Anleitung zur Blutzuckermessung",
    "620": "Erfolgszuschlag für Anleitung zur Dekubitusbehandlung",
    "621": "Erfolgszuschlag für Anleitung zu Drainagen, Überprüfen von, Versorgen",
    "622": "Erfolgszuschlag für Anleitung zum Einlauf",
    "623": "Erfolgszuschlag für Anleitung Klistier / Klysma",
    "624": "Erfolgszuschlag für Anleitung zur digitalen Enddarmausräumung",
    "625": "Erfolgszuschlag für Anleitung zur Flüssigkeitsbilanzerung",
    "626": "Erfolgszuschlag für Anleitung Infusionen, Überwachen von",
    "627": "Erfolgszuschlag für Anleitung zur Inhalation",
    "628": "Erfolgszuschlag für Anleitung zur s.c. Injektion - Insulin",
    "629": "Erfolgszuschlag für Anleitung zur s.c. Injektion – sonstige Medikamente",
    "630": "Erfolgszuschlag für Anleitung zur Injektion i.m.",
    "631": "Erfolgszuschlag für Anleitung zur Injektion, Richten von",
    "632": "Erfolgszuschlag für Anleitung zur Instillation",
    "633": "Erfolgszuschlag für Anleitung zum Auflegen von Kälteträgern",
    "634": "Erfolgszuschlag für Anleitung zur Versorgung eines suprapubischen Katheters",
    "635": "Erfolgszuschlag für Anleitung zur Katheterisierung",
    "636": "Erfolgszuschlag für Anleitung spezielle Krankenbeobachtung",
    "637": "Erfolgszuschlag für Anleitung zum Legen und Wechseln einer Magensonde",
    "638": "Erfolgszuschlag für Anleitung zur Medikamentengabe",
    "639": "Erfolgszuschlag für Anleitung zum Richten von Medikamenten",
    "640": "Erfolgszuschlag für Anleitung zum Augentropfen",
    "641": "Erfolgszuschlag für Anleitung zum Ohren-/Augentropfen",
    "642": "Erfolgszuschlag für Anleitung zur PEG",
    "643": "Erfolgszuschlag für Anleitung zur Stomabehandlung",
    "644": "Erfolgszuschlag für Anleitung zur Pflege und Wechsel der Trachealkanüle",
    "645": "Erfolgszuschlag für Anleitung zur Pflege des zentralen Venenkatheters",
    "646": "Erfolgszuschlag für Anleitung zum Anlegen und Wechseln von Wundverbänden",
    "647": "Erfolgszuschlag für Anleitung Kompressionsverbände",
    "648": "Erfolgszuschlag für Anleitung zum Anziehen von Kompressionsstrümpfen",
    "649": "Erfolgszuschlag für Anleitung zum Ausziehen von Kompressionsstrümpfen",
    "650": "Abzug je Einsatz bei Medikamentengabe in Einrichtungen des betreuten Wohnens o. b. Versorgung mehrer Personen im gleichem Haushalt",
    "651": "Abzug je Einsatz bei allen anderen Pflegetätigkeiten in Einrichtungen des betreuten Wohnens o. b. Versorgung mehrer Personen im gleichem Haushalt",
    "652": "Abzug aufgrund Zusammentreffen von Medigabe und SGB XI-Leistungen",
    "653": "Abzug zur Pauschale 170 bei Zusammentreffen von Leistungen nach SGB XI und SGB V",
    "654": "Zuschlag bei Intensivpflege",
    "655": "Zuschlag für Intensivpflege-Einsätze von 20.00 Uhr - 06.00 Uhr oder an Sonn- und Feiertagen",
    "660": "Erfolgszuschlag für Anleitung zum Anlegen von stützenden und stabilisierenden Verbänden",
    "661": "Erfolgszuschlag für Anleitung zur Bronchialtoilette",
    "662": "Erfolgszuschlag für Anleitung zum Absaugen",
    "663": "Erfolgszuschlag für Anleitung zu medizinischen Bädern",
    "664": "Erfolgszuschlag für Anleitung zu Einreibungen",
    "665": "Zuschlag, wenn eine oder mehrere Infusionen beim Hausbesuch verabreicht werden",
    "666": "Abzug zur Position 121",
    "667": "Abzug zur Position 124",
    "668": "Abzug zur Position 126",
    "669": "Abzug zur Position 233",
    "670": "Abzug zur Position 274",
    "671": "Abzug zur Position 277",
    "672": "Abzug zur Position 107",
    "673": "Abzug zur Position 108",
    "674": "Abzug zur Position 109",
    "675": "Abzug zur Position 155",
    "676": "Abzug zur Position 156",
    "677": "Abzug zur Position 157",
    "678": "Abschlag § 37 Abs. 1 SGB V bis 4 Wochen",
    "679": "Abschlag § 37 Abs. 1 SGB V ab 5. Woche",
    "680": "Abschlag Leistungsgruppe 1",
    "681": "Abschlag Leistungsgruppe 2",
    "682": "Abschlag Leistungsgruppe 3",
    "683": "Abschlag Leistungsgruppe 4",
    "684": "Abschlag Anleitung Leistungsgruppe 1",
    "685": "Abschlag Anleitung Leistungsgruppe 2",
    "686": "Abschlag Anleitung Leistungsgruppe 3",
    "687": "Abschlag Anleitung Leistungsgruppe 4",
    "688": "Abschlag Anleitungserfolg Leistungsgruppe 1",
    "689": "Abschlag Anleitungserfolg Leistungsgruppe 2",
    "690": "Abschlag Anleitungserfolg Leistungsgruppe 3",
    "691": "Abschlag Anleitungserfolg Leistungsgruppe 4",
    "692": "Abschlag psychiatrische HKP",
    "693": "Abschlag psychiatrische HKP und Leistungsgruppe 1",
    "694": "Abschlag psychiatrische HKP und Leistungsgruppe 2",
    "695": "Abschlag psychiatrische HKP und Leistungsgruppe 3",
    "696": "Abschlag psychiatrische HKP und Leistungsgruppe 4",
    "697": "Abschlag Sonderversorgung nach § 37 Abs. 1 SGB V",
    "698": "Abschlag Sonderversorgung nach § 37 Abs. 2 SGB V",
    "699": "Einsatz für nicht Besondere Wohnform",
    "700": "Einsatzzuschlag Psychiatrische Häusliche Krankenpflege",
    "740": "Zuschlag je Stunde für alte Bundesländer und Berlin",
    "741": "Abzug je Stunde bei Pflegestufe I",
    "742": "Abzug je Stunde bei Pflegestufe II",
    "743": "Abzug je Stunde bei Pflegestufe III",
    "744": "Abzug je Stunde bei Pflegestufe III Härtefall",
    "745": "Zuschlag für spezielle Schutzkleidung aufgrund eines Krankheitsbildes des Versicherten",
    "901": "Zuschlag bei zeitgleicher Erbringung somatischer HKP und psychiatrischer HKP pro Einsatz",
    "751": "Erfolgszuschlag zum Anlegen eines Kompressionsverbandes",
    "752": "Abschlag für Einsatz in Besonderer Wohnform/Betreutem Wohnen",
    "913": "Zuschlag für kurzzeitige Einsätze je Stunde (Kinder)",
    "914": "Zuschlag für kurzzeitige Einsätze je Stunde (Erwachsene)",
    "915": "Zuschlag für besondere Versorgungssituationen / besonders aufwändige Versorgungsformen je Stunde (Kinder)",
    "916": "Zuschlag für besondere Versorgungssituationen / besonders aufwändige Versorgungsformen je Stunde (Erwachsene)",
    "922": "MRSA Zuschlag",
    "931": "Hausbesuch an Samstagen, Sonn- und Feiertagen",
    "932": "Hausbesuch an Samstagen, Sonn- und Feiertagen, halb",
    "933": "Hausbesuch an Samstagen, Sonn- und Feiertagen, geviertelt, Angehöriger und Pflegeversicherung",
    "978": "Abzug je Stunde bei Pflegestufe 0 - Versicherte mit dauerhaft erheblicher Einschränkung der Alltagskompetenz i. S. von § 45 a SGB XI",
    "979": "Abzug je Stunde bei Pflegestufe I - Versicherte mit dauerhaft erheblicher Einschränkung der Alltagskompetenz i. S. von § 45 a SGB XI",
    "980": "Abzug je Stunde bei Pflegestufe II - Versicherte mit dauerhaft erheblicher Einschränkung der Alltagskompetenz i. S. von § 45 a SGB XI",
    "A19": "Erfolgszuschlag für Anleitung zur intensivierten Insulintherapie",
    "A73": "Abzug je Stunde bei Pflegegrad 2",
    "A74": "Abzug je Stunde bei Pflegegrad 3",
    "A75": "Abzug je Stunde bei Pflegegrad 4",
    "A76": "Abzug je Stunde bei Pflegegrad 5",
    "B02": "Hausbesuch mehrerer Patienten nachts ohne Sachleistungen der Pflegeversicherung",
    "B20": "Zuschlag zur Grundpflege und hauswirtschaftlichen Versorgung nach § 37 Abs. 1a SGB V",
    "B66": "Allgemeiner Zuschlag für Fachkräfteeinsatz",
    "B67": "Allgemeiner Zuschlag bei Anleitung Fachkräfteeinsatz",
    "B68": "Zuschlag A",
    "B69": "Zuschlag B",
    "B70": "Abschlag A",
    "B71": "Abschlag B",
    "B73": "MRSA Zuschlag je Hausbesuch ohne Leistungen SGB XI",
    "B74": "MRSA Zuschlag je Hausbesuch mit Leistungen SGB XI",
    "B75": "Zuschlag Intensivpflege Stufe 1 – Sonderzahlungen/Patient vom 1. bis 4. Monat",
    "B76": "Zuschlag Intensivpflege Stufe 2 – Sonderzahlungen/Patient vom 5. bis 8. Monat",
    "B77": "Zuschlag Intensivpflege Stufe 3 – Sonderzahlungen/Patient vom 9. bis 12. Monat",
    "C07": "Zuschlag zur Vergütung von Intensivpflege in ambulanten Wohneinrichtungen je Stunde für Einzelversorgungen",
    "C08": "Zuschlag ab der 3. Leistung innerhalb eines Einsatzes - Leistungsgruppe 1",
    "C09": "Zuschlag ab der 3. Leistung innerhalb eines Einsatzes - Leistungsgruppe 2",
    "C10": "Zuschlag ab der 3. Leistung innerhalb eines Einsatzes - Leistungsgruppe 3",
    "C11": "Zuschlag ab der 3. Leistung innerhalb eines Einsatzes - Leistungsgruppe 4",
    "C12": "Zuschlag ab der 3. Leistung innerhalb eines Einsatzes - Leistungsgruppe 5",
    "C19": "Zuschlag ab der 3. Leistung innerhalb eines Einsatzes + 2. PK - Leistungsgruppe 1",
    "C20": "Zuschlag ab der 3. Leistung innerhalb eines Einsatzes + 2. PK - Leistungsgruppe 2",
    "C21": "Zuschlag ab der 3. Leistung innerhalb eines Einsatzes + 2. PK - Leistungsgruppe 3",
    "C22": "Zuschlag ab der 3. Leistung innerhalb eines Einsatzes + 2. PK - Leistungsgruppe 4",
    "C23": "Zuschlag ab der 3. Leistung innerhalb eines Einsatzes + 2. PK - Leistungsgruppe 5",
    "C96": "Zuschlag - Positionswechsel zur Dekubitusbehandlung (zwischen 21 und 6 Uhr)",
    "C97": "Zuschlag 2. PK - Positionswechsel zur Dekubitusbehandlung (zw. 21 und 6 Uhr)",
    "C98": "Zuschlag 2. PK - Einsatzpauschale MRE",
}
export type ZuschlaegeAbzuegeVerguetungsArtSchluessel = keyof typeof zuschlaegeAbzuegeVerguetungsArtSchluessel

/** Hausbesuche / Wegegeld */
export const hausbesucheWegegeldVerguetungsArtSchluessel = {
    "701": "Hausbesuch",
    "702": "Hausbesuch mehrerer Patienten (z.B. in einer Einrichtung/Gemeinschaft)",
    "703": "Hausbesuch bis 3 km",
    "704": "Hausbesuch bis 2 km",
    "705": "Hausbesuch bis 11 km",
    "706": "Wegegeldpauschale",
    "707": "Wegegeld je km",
    "708": "Wegegeld je Doppelkilometer",
    "709": "Wegegeld pauschal. in geschl. Ortschaften",
    "710": "Wegegeld je Kilometer bei Überschreiten der Ortsgrenze",
    "711": "Wegegeld pauschal bis 15 km",
    "712": "öffentliche Verkehrsmittel",
    "713": "Hausbesuch mit Sachleistungen der Pflegeversicherung",
    "714": "Hausbesuch mehrerer Patienten mit Sachleistungen der Pflegeversicherung",
    "715": "Wegegeldpauschale mit Sachleistungen der Pflegeversicherung",
    "716": "Hausbesuch ohne Sachleistungen der Pflegeversicherung (Sa, So, gesetzl. Feiertag)",
    "717": "Hausbesuch mehrerer Patienten ohne Sachleistungen der Pflegeversicherung (Sa, So, gesetzl. Feiertag)",
    "718": "Hausbesuch mit Sachleistungen der Pflegeversicherung (Sa, So, gesetzl. Feiertag)",
    "719": "Hausbesuch mehrer Patienten mit Sachleistungen der Pflegeversicherung (Sa, So, gesetzl. Feiertag)",
    "720": "Hausbesuch Tag geviertelt Angehöriger und Pflegeversicherung",
    "721": "Hausbesuch Nacht ganz",
    "722": "Hausbesuch Halb Angehöriger",
    "723": "Hausbesuch Nacht halb",
    "724": "Hausbesuch Nacht geviertelt Angehöriger und Pflegeversicherung",
    "725": "Wegepauschale (für den 1. und 2. Einsatz)",
    "726": "Wegepauschale (für den 3. - 5. Einsatz)",
    "727": "Wegepauschale bei zeitgleicher Leistungserbringung nach SGB V / SGB XI (1. und 2. Einsatz)",
    "728": "Wegepauschale bei zeitgleicher Leistungserbringung nach SGB V / SGB XI (3. - 5. Einsatz)",
    "729": "Wegegeld je Kilometer bei mehreren Patienten",
    "730": "Wegegeld je Kilometer mit Sachleistungen der Pflegeversicherung",
    "731": "Wegegeld je Kilometer mit Sachleistungen der Pflegeversicherungund mehreren Patienten",
    "732": "Hausbesuchspauschale ohne Ausschlusstatbestände (bei bis zu drei Einsätzen pro Tag)",
    "733": "Hausbesuchspauschale ohne Ausschlusstatbestände (bei vier und mehr Einsätzen pro Tag)",
    "734": "Wegegeld pauschal über 15 km",
    "735": "Wegegeld pauschal bis 40 km",
    "736": "Wegegeld pauschal über 40 km",
    "737": "xxx Fahrzeit bis zu 15 Min.",
    "738": "xxx Fahrzeit bis zu 30 Min.",
    "739": "xxx Fahrzeit bis zu 45 Min.",
    "746": "xxx Fahrzeit bis zu 60 Min.",
    "747": "xxx Fahrzeit bis zu 75 Min.",
    "748": "xxx Fahrzeit bis zu 90 Min.",
    "749": "Höchstbetrag einfache Fahrt",
    "750": "Höchstbetrag Fahrzeit je Tag",
    "896": "Hausbesuch Intensivpflege",
    "897": "Nachthausbesuch Intensivpflege",
    "898": "Wegegeld je km Intensivpflege",
    "A90": "HB-Gebühr in amb.betr.WG (kein integrierter Pflegedienst) HKP alleine (08:00 Uhr – 20:00 Uhr)",
    "A91": "HB-Gebühr in amb.betr.WG (kein integrierter Pflegedienst) mit SGB XI (08:00 Uhr – 20:00 Uhr)",
    "A93": "HB-Gebühr in amb.betr.WG (kein integrierter Pflegedienst) HKP alleine (20.01 Uhr – 07.59 Uhr)",
    "A94": "HB-Gebühr in amb.betr.WG (kein integrierter Pflegedienst) mit SGB XI (20.01 Uhr – 07.59 Uhr)",
    "B50": "Hausbesuch 3 Personen",
    "B51": "Hausbesuch 3 Personen mit Leistungen SGB XI",
    "B52": "Hausbesuch 4 Personen",
    "B53": "Hausbesuch 4 Personen mit Leistungen SGB XI",
    "C66": "Hausbesuchsgebühr in ambulant betreuter WG, HKP alleine, kein integrierter Pflegedienst (tagsüber)",
    "C67": "Hausbesuchsgebühr in ambulant betreuter WG, mit SGB XI, kein integrierter Pflegedienst (tagsüber)",
    "C68": "Hausbesuchsgebühr in ambulant betreuter WG, HKP alleine, kein integrierter Pflegedienst (nachts)",
    "C69": "Hausbesuchsgebühr in ambulant betreuter WG, mit SGB XI, kein integrierter Pflegedienst (nachts)",
}
export type HausbesucheWegegeldVerguetungsArtSchluessel = keyof typeof hausbesucheWegegeldVerguetungsArtSchluessel

/** Ergänzender HKP-Anspruch § 37 Abs. 2 Satz 3 SGB V / Finanzierungsbestandteile aus SGBXI */
export const hkpAnspruchSGBXIVerguetungsArtSchluessel = {
    "C36": "Pflegebedingte Aufwendungen monatlich",
    "C37": "Unterkunft und Verpflegung monatlich",
    "C38": "Ausbildungsumlage-Zuschlag monatlich",
    "C39": "Sachleistungsbezug nach § 43 SGB XI mtl.",
    "C40": "ABUZ PflegeberufeG",
    "C41": "Betriebsnotwendige Investitionskosten a.) mtl.",
    "C42": "Betriebsnotwendige Investitionskosten b.) mtl.",
    "C43": "Betriebsnotwendige Investitionskosten c.) mtl.",
    "C44": "Betriebsnotwendige Investitionskosten d.) mtl.",
    "C45": "Pflegebedingte Aufwendungen monatlich Grad 2",
    "C46": "Pflegebedingte Aufwendungen monatlich Grad 3",
    "C47": "Pflegebedingte Aufwendungen monatlich Grad 4",
    "C48": "Pflegebedingte Aufwendungen monatlich Grad 5",
    "C49": "Nachgehender Anspruch Finanzierungsanteil SGB XI IPREG",
    "C50": "Pflegebedingte Aufwendungen - Teilzeitraum",
    "C51": "Unterkunft und Verpflegung - Teilzeitraum",
    "C52": "Ausbildungsumlage - Teilzeitraum",
    "C53": "ABUZ PflegeberufeG - Teilzeitraum",
    "C54": "Vergütung Teilzeitraum gesamt",
    "C55": "Abzug Besitzstand PSG",
    "C56": "Abzug Beihilfe gesamt",
    "C57": "Abzug SGB XI Leistungsbetrag gesamt",
    "C58": "Abzug SGB XI monatlich Grad 2",
    "C59": "Abzug SGB XI monatlich Grad 3",
    "C60": "Abzug SGB XI monatlich Grad 4",
    "C61": "Abzug SGB XI monatlich Grad 5",
    "C63": "Aufwendungen nach § 82b SGB XI",
    "C85": "Abzug Sondennahrung mtl",
    "C86": "Abzug Sondennahrung Teilmonat",
    "C87": "Abzug Behandlungspflege Teilmonat",
    "C88": "Betriebsnotwendige Investitionskosten e.) mtl",
    "C89": "Betriebsnotwendige Investitionskosten f.) mtl",
    "C90": "Betriebsnotwendige Investitionskosten a.) Teilmonat",
    "C91": "Betriebsnotwendige Investitionskosten b.) Teilmonat",
    "C92": "Betriebsnotwendige Investitionskosten c.) Teilmonat",
    "C93": "Betriebsnotwendige Investitionskosten d.) Teilmonat",
    "C94": "Betriebsnotwendige Investitionskosten e.) Teilmonat",
    "C95": "Betriebsnotwendige Investitionskosten f.) Teilmonat",
}
export type HKPAnspruchSGBXIVerguetungsArtSchluessel = keyof typeof hkpAnspruchSGBXIVerguetungsArtSchluessel
