/** based on documents
 *  - Gemeinsames Rundschreiben, Anlage 08, Staatsangehörigkeit und Länderkennzeichen für Auslandsanschriften
 * 
 * see docs/documents.md for more info
 */

/** Länderkennzeichen
 *  
 *  Key to be used when specifying the places of residence outside Germany */
 export const laenderkennzeichenSchluessel = {
    // not in alphabetical order, but in the order they appear in the documentation, with duplicates
    // merged (such as "E": "Mellila", "E": "Spain")
    "AFG": "Afghanistan",
    "ET": "Ägypten",
    "AX": "Åland",
    "AL": "Albanien",
    "DZ": "Algerien",
    "AJ": "Amerik.-Jungferninseln",
    "AS": "Amerik.-Samoa",
    "AND": "Andorra",
    "AGO": "Angola",
    "ANG": "Anguilla",
    "ANT": "Antigua und Barbuda",
    "AQU": "Äquatorialguinea",
    "RA": "Argentinien",
    "ARM": "Armenien",
    "AW": "Aruba",
    "ASE": "Aserbaidschan",
    "AU": "Ashmore- und Cartierinseln, Korallenmeerinseln",
    "ETH": "Äthiopien",
    "AUS": "Australien",
    "AQ": "Antarktis",
    "BS": "Bahamas",
    "BRN": "Bahrain",
    "BD": "Bangladesch",
    "BDS": "Barbados",
    "B": "Belgien",
    "BH": "Belize",
    "DY": "Benin",
    "BER": "Bermuda",
    "BHT": "Bhutan",
    "BOL": "Bolivien",
    "BQ": "Bonaire, Saba, St. Eustatius",
    "BIH": "Bosnien und Herzegowina",
    "RB": "Botsuana",
    "BV": "Bouvetinsel",
    "BR": "Brasilien",
    "BJ": "Britische Jungferninseln",
    "IO": "Britisches Territorium im Indischen Ozean",
    "BRU": "Brunei Darussalam",
    "BG": "Bulgarien",
    "HV": "Burkina Faso",
    "RU": "Burundi",
    "CV": "Cabo Verde",
    "RCH": "Chile",
    "TJ": "China",
    "CP": "Clipperton",
    "COI": "Cookinseln",
    "CR": "Costa Rica",
    "CI": "Cote d´Ivoire",
    "CW": "Curaçao",
    "DK": "Dänemark",
    "D": "Deutschland",
    "WD": "Dominica",
    "DOM": "Dominikanische Republik",
    "DSC": "Dschibuti",
    "EC": "Ecuador",
    "ES": "El Salvador",
    "ERI": "Eritrea",
    "EST": "Estland",
    "FAL": "Falklandinseln",
    "FR": "Färöer",
    "FJI": "Fidschi",
    "FIN": "Finnland",
    "F": "Frankreich",
    "TF": "Französische Süd- und Antarktisgebiete",
    "FG": "Französisch-Guayana",
    "FP": "Französisch-Polynesien",
    "GAB": "Gabun",
    "WAG": "Gambia",
    "GEO": "Georgien",
    "GH": "Ghana",
    "GIB": "Gibraltar",
    "WG": "Grenada",
    "GR": "Griechenland",
    "GRO": "Grönland",
    "GUA": "Guadeloupe",
    "GUM": "Guam",
    "GCA": "Guatemala",
    "GG": "Guernsey",
    "RG": "Guinea",
    "GUB": "Guinea-Bissau",
    "GUY": "Guyana",
    "RH": "Haiti",
    "HM": "Heard und McDonaldinseln",
    "HCA": "Honduras",
    "HKG": "Hongkong",
    "IND": "Indien",
    "RI": "Indonesien",
    "MAN": "Insel Man",
    "IRQ": "Irak",
    "IR": "Iran",
    "IRL": "Irland",
    "IS": "Island",
    "IL": "Israel",
    "I": "Italien",
    "JA": "Jamaika",
    "J": "Japan",
    "YEM": "Jemen",
    "JE": "Jersey",
    "JOR": "Jordanien",
    "KAI": "Kaimaninseln",
    "K": "Kambodscha",
    "CAM": "Kamerun",
    "CDN": "Kanada",
    "KAS": "Kasachstan",
    "QAT": "Katar",
    "EAK": "Kenia",
    "KIS": "Kirgisistan",
    "KIB": "Kiribati",
    "UM": "Navassa, Kleinere Amerikanische Überseeinseln",
    "CC": "Kokosinseln",
    "CO": "Kolumbien",
    "KOM": "Komoren",
    "RCB": "Kongo",
    "ZRE": "Demokratische Republik Kongo",
    "KOR": "Demokratische Volksrepublik Korea",
    "ROK": "Republik Korea",
    "KOS": "Kosovo",
    "HR": "Kroatien",
    "C": "Kuba",
    "KWT": "Kuwait",
    "LAO": "Laos",
    "LS": "Lesotho",
    "LV": "Lettland",
    "RL": "Libanon",
    "LB": "Liberia",
    "LAR": "Libyen",
    "FL": "Liechtenstein",
    "LT": "Litauen",
    "L": "Luxemburg",
    "MAC": "Macau",
    "RM": "Madagaskar",
    "MW": "Malawi",
    "MAL": "Malaysia",
    "BIO": "Malediven",
    "RMM": "Mali",
    "M": "Malta",
    "MA": "Marokko",
    "MAR": "Marshallinseln",
    "MAT": "Martinique",
    "RIM": "Mauretanien",
    "MS": "Mauritius",
    "MAY": "Mayotte",
    "MK": "Mazedonien",
    "MEX": "Mexiko",
    "MIK": "Mikronesien",
    "MD": "Moldau",
    "MC": "Monaco",
    "MON": "Mongolei",
    "MNE": "Montenegro",
    "MOT": "Montserrat",
    "MOZ": "Mosambik",
    "MYA": "Myanmar",
    "SWA": "Namibia",
    "NAU": "Nauru",
    "NEP": "Nepal",
    "NKA": "Neukaledonien",
    "NZ": "Neuseeland",
    "NIC": "Nicaragua",
    "NL": "Niederlande",
    "RN": "Niger",
    "WAN": "Nigeria",
    "NIU": "Niue",
    "MP": "Nördliche Marianen und Marianen",
    "N": "Norwegen",
    "MAO": "Oman",
    "A": "Österreich",
    "PK": "Pakistan",
    "PSE": "Palästinensische Gebiete",
    "PAL": "Palau",
    "PA": "Panama",
    "PNG": "Papua-Neugiunea",
    "PY": "Paraguay",
    "PE": "Peru",
    "RP": "Philippinen",
    "PIT": "Pitcairninsel",
    "PL": "Polen",
    "P": "Portugal",
    "PRI": "Puerto Rico",
    "REU": "Réunion",
    "RWA": "Ruanda",
    "RO": "Rumänien",
    "RUS": "Russische Föderation",
    "PIE": "Saint Pierre und Miquelon",
    "SOL": "Salomonen",
    "Z": "Sambia",
    "WS": "Samoa",
    "RSM": "San Marino",
    "STP": "Sao Tomé und Principe",
    "SAU": "Saudi-Arabien",
    "S": "Schweden",
    "CH": "Schweiz",
    "SN": "Senegal",
    "SRB": "Serbien",
    "SY": "Seychellen",
    "WAL": "Sierra Leone",
    "ZW": "Simbabwe",
    "SGP": "Singapur",
    "SK": "Slowakei",
    "SLO": "Slowenien",
    "SP": "Somalia",
    "E": "Spanien",
    "CL": "Sri Lanka",
    "BL": "St. Barthélemy",
    "HEL": "St. Helena, Ascension, Tristan da Cunha",
    "SCN": "St. Kitts und Nevis",
    "WL": "St. Lucia",
    "MF": "St. Martin (französischer Teil)",
    "SX": "St. Martin (niederländischer Teil)",
    "WV": "St. Vincent und die Grenadinen",
    "ZA": "Südafrika",
    "SDN": "Sudan",
    "GS": "Südgeorgien und die südlichen Sandwichinseln",
    "SSD": "Südsudan",
    "SME": "Suriname",
    "SJ": "Svalbard und Jan Mayen",
    "SD": "Swasiland",
    "SYR": "Syrien",
    "TAD": "Tadschikistan",
    "RC": "Taiwan",
    "EAT": "Tansania",
    "T": "Thailand",
    "OTI": "Timor-Leste",
    "TG": "Togo",
    "TOK": "Tokelau",
    "TON": "Tonga",
    "TT": "Trinidad und Tobago",
    "CHD": "Tschad",
    "CZ": "Tschechien",
    "TN": "Tunesien",
    "TR": "Türkei",
    "TUR": "Turkmenistan",
    "TUC": "Turks- und Caicosinseln",
    "TUV": "Tuvalu",
    "EAU": "Uganda",
    "UA": "Ukraine",
    "H": "Ungarn",
    "ROU": "Uruguay",
    "USB": "Usbekistan",
    "VAN": "Vanuatu",
    "V": "Vatikanstadt",
    "YV": "Venezuela",
    "UAE": "Vereinigte Arabische Emirate",
    "USA": "Vereinigte Staaten",
    "GB": "Vereinigtes Königreich",
    "VN": "Vietnam",
    "WF": "Wallis und Futuna",
    "CX": "Weihnachtsinsel",
    "BY": "Weißrußland",
    "EH": "Westsahara",
    "RCA": "Zentralafrikanische Republik",
    "CY": "Zypern",
    // old values, some old people may still have those assigned
    "SCG": "Serbien und Montenegro",
    "YU": "Jugoslawien",
    "KAN": "Kanalinseln",
    "SUD": "Sudan (vor der Teilung des Landes)",
    "NLA": "Niederländische Antillen einschl. Curacao",
    "NMA": "Nördliche Marianen",
    "PIN": "Pazifische Inseln (Marianen- und Karolineninseln)"
}

export type LaenderkennzeichenSchluessel = keyof typeof laenderkennzeichenSchluessel
